In [1]:
import pandas as pd

In [80]:
df = pd.read_csv('/home/wenyuantong/Desktop/data/arabi_heterotypic_clusers_mpipi.csv')
display(df.head())

,index,UniProt ID,name,cluster,idr_start,idr_end,sequence
0,1,Q0WVH7,tr|Q0WVH7|Q0WVH7_ARATH Protein SDA1 OS=Arabid...,1,510,651,VFSNVPNVELLQESDNESGSDGDQDDDGVELPIGDDVEQELIPGD...
1,2,Q7XA71,tr|Q7XA71|Q7XA71_ARATH At2g22080 OS=Arabidops...,1,50,177,DVIENGYEVVDAVEGNGNNDDSGDDGGEDEEGSADDAEGKETKKG...
2,3,A0A1I9LQY7,tr|A0A1I9LQY7|A0A1I9LQY7_ARATH N-lysine methy...,1,156,293,NVDSDSFGIKEYLAAKSLIASRSFEIDDYHGSGMVPLADLFNHKT...
3,4,Q9LVG1,sp|Q9LVG1|Y5013_ARATH B3 domain-containing pr...,1,118,230,RSSDQSEEIKVESDSDEQNQASDDVLSLDEDDDDSDYNCGEDNDS...
4,5,Q9LST3,sp|Q9LST3|Y5142_ARATH B3 domain-containing pr...,1,123,245,LDDNDDGFNDDQDYGEEVKSSENFIVLDDDDISDVQDYNEEDTSS...

In [81]:
print("Column names of the DataFrame:")
print(df.columns)

Column names of the DataFrame:
Index(['index', ' UniProt ID', ' name', ' cluster', ' idr_start', ' idr_end',
       ' sequence'],
      dtype='object')

In [90]:
# Filter the DataFrame for rows where 'cluster' is 1
filtered_df = df[df[' cluster'] == 3]

# Get the 'UniProt ID' column from the filtered DataFrame and convert it to a list
uniprot_ids_in_cluster_1 = filtered_df[' UniProt ID'].tolist()

print("\nUniProt IDs for rows where 'cluster' is 1:")
print(uniprot_ids_in_cluster_1)

UniProt IDs for rows where 'cluster' is 1:
[' A0A1P8BBR6', ' Q9C633', ' Q9SZU4', ' Q8LCS6', ' C0Z225', ' O81834', ' Q9STW1', ' Q9LZE2', ' F4KH50', ' Q9ZVU2', ' F4J7B4', ' F4J6D7', ' Q94A40', ' F4J5Z7', ' O49733', ' Q9FLX8', ' Q9SHD0', ' Q94GA6', ' A0A1P8B5V8', ' A0A178WDK9', ' Q38798', ' Q9FG23', ' F4IXU3', ' O64760', ' Q9C813', ' Q9S793', ' Q9LZU7', ' Q9FM29', ' Q9FY67', ' O82491', ' F4IDC2', ' A0A1P8B664', ' A0A1P8ANT8', ' B9DFG3', ' O80668', ' Q9SD55', ' Q9LSH4', ' Q9FML9', ' A0MFS5', ' Q9FF55', ' Q9SJT9', ' A0A1P8APK6', ' F4J4Q8', ' F4J4R5', ' Q9LVA7', ' Q0WRC9', ' F4JGK7', ' Q9SK71', ' F4JSB9', ' A0A1P8BDX4', ' F4HZY1', ' Q67XL4', ' Q8H0V8', ' Q9LEZ1', ' Q93VI4', ' Q9FNY8', ' Q9LES2', ' Q9M082', ' Q9C6G8', ' Q8LPL8', ' Q9LTB9', ' F4I765', ' F4I552']

In [85]:
print(",".join(uniprot_ids_in_cluster_1))

 Q0WP38, Q0WTB4, F4JCC9, O48523, Q9CAE0, F4K487, Q9LUA2, Q9FFX6, Q94CK1, Q9FFH0, Q9FYD1, F4IVU7, Q681J0, Q9SRD6, Q9SL79, Q946J8, Q9FNR0, Q9FMU5, Q9C9S1, Q7X9V2, B9DF92, Q5XVK1, Q700C7, Q9SVY0, P55034, Q9LDA9, Q9CAJ0, F4HW51, Q84W65, Q9S7L9, O49466, Q9SK74, Q8VY58, F4I131, Q56XZ5, Q9C923, Q9XID0, Q9ZVX1, O04716, Q8GUP0, F4K4D6, F4I4Y6, Q93ZL5, O65370, Q8L7U4, Q9FIF4, F4K6R6, P0DMS1, Q9MAT6, Q8L626, Q9FJW6, F4JA78, F4JEI7, Q9FFH1, Q6NKT5, Q84JB7, F4I2J8, F4JRF4, F4J7V7, Q9CAV7, Q56Z59, Q9M0B2, F4I4Q1

In [8]:
print(df.columns)

,index,UniProt ID,name,cluster,idr_start,idr_end,sequence
0,1,Q0WVH7,tr|Q0WVH7|Q0WVH7_ARATH Protein SDA1 OS=Arabid...,1,510,651,VFSNVPNVELLQESDNESGSDGDQDDDGVELPIGDDVEQELIPGD...
1,2,Q7XA71,tr|Q7XA71|Q7XA71_ARATH At2g22080 OS=Arabidops...,1,50,177,DVIENGYEVVDAVEGNGNNDDSGDDGGEDEEGSADDAEGKETKKG...
2,3,A0A1I9LQY7,tr|A0A1I9LQY7|A0A1I9LQY7_ARATH N-lysine methy...,1,156,293,NVDSDSFGIKEYLAAKSLIASRSFEIDDYHGSGMVPLADLFNHKT...
3,4,Q9LVG1,sp|Q9LVG1|Y5013_ARATH B3 domain-containing pr...,1,118,230,RSSDQSEEIKVESDSDEQNQASDDVLSLDEDDDDSDYNCGEDNDS...
4,5,Q9LST3,sp|Q9LST3|Y5142_ARATH B3 domain-containing pr...,1,123,245,LDDNDDGFNDDQDYGEEVKSSENFIVLDDDDISDVQDYNEEDTSS...
5,6,Q9FKW0,sp|Q9FKW0|RNG1A_ARATH Putative E3 ubiquitin-p...,1,1,124,MSVKNNSFSSAEIPDVADQPRDRFNPEATQDLQEKDETKEEKEGD...
6,7,A0A1P8BD18,tr|A0A1P8BD18|A0A1P8BD18_ARATH rRNA processin...,1,1,128,MRLSIALKVVKMAGGSKRSKRARLDSESEDISDQENLKAESDNED...
7,8,Q9FNE4,sp|Q9FNE4|PDP3_ARATH PWWP domain-containing p...,1,1,124,MEIEVVLGIGEDAGPKPCSAEIESAEKTLKDDGVVQENGVRVSDN...
8,9,F4JG98,tr|F4JG98|F4JG98_ARATH Cystatin/monellin supe...,1,1,124,MEIPPIETTTDESTVACSLNKDISDSDTREDDYSSDGEKEGEDYE...
9,10,Q8GYP3,sp|Q8GYP3|RDM4_ARATH RNA-directed DNA methyla...,1,203,346,TAAEEIEADIQSSHTEEYVYDYYAVNEEMDISEDSSKNQFPLVIV...
10,11,Q9FFP0,tr|Q9FFP0|Q9FFP0_ARATH RBR-type E3 ubiquitin ...,1,1,143,MENDQQGSYLRDEDKEEMEKRIRTVVIDSNLVLSNSTCGICRTAE...
11,12,A0A178UWL0,tr|A0A178UWL0|A0A178UWL0_ARATH Transducin/WD4...,1,436,541,DYDDELFGNGMDIGIDGNEGEDESIDDDAEDNDDDSDYSSGVDLD...
12,13,A0A178VM97,tr|A0A178VM97|A0A178VM97_ARATH Uncharacterize...,1,1,146,MDDWSDFFDICDEGCDLDYHSDGYSYEGDFDFDYPYGEDINDCYA...
13,14,Q9FHB0,sp|Q9FHB0|Y5014_ARATH B3 domain-containing pr...,1,110,236,TTCKRLKRSSEQSKDIIKVGSDCEEESQASDDVIVLNSDDSDDSD...
14,15,F4IXX4,tr|F4IXX4|F4IXX4_ARATH Transcription factor I...,1,434,574,QKETLKPSLVKHREATKGSEDMETFKSVNENVDANVNEDGEDENL...
15,16,Q9ASP6,sp|Q9ASP6|HNRPQ_ARATH Heterogeneous nuclear r...,1,1,103,MSDARDNDDRVDFEEGSYSEMEDEVEEEQVEEYEEEEEEDDDDDD...
16,17,Q9SZI2,sp|Q9SZI2|NAP1A_ARATH Nucleosome assembly pro...,1,231,372,KNTKPITKLEDCESFFNFFSPPEVPDEDEDIDEERAEDLQNLMEQ...
17,18,Q9M086,sp|Q9M086|DCAF1_ARATH DDB1- and CUL4-associat...,1,1753,1883,QEDMFSSARMYEIGRRRPTDDDSDPDDDDETEDEDEDDEEEDDLD...

In [21]:
print(",".join(new_list))

Q0WVH7,Q7XA71,A0A1I9LQY7,Q9LVG1,Q9LST3,Q9FKW0,A0A1P8BD18,Q9FNE4,F4JG98,Q8GYP3,Q9FFP0,A0A178UWL0,A0A178VM97,Q9FHB0,F4IXX4,Q9ASP6,Q9SZI2,Q9M086

In [19]:
new_list = [s.replace(' ', '') for s in uniprot_ids_in_cluster_1]

In [20]:
print(new_list)

['Q0WVH7', 'Q7XA71', 'A0A1I9LQY7', 'Q9LVG1', 'Q9LST3', 'Q9FKW0', 'A0A1P8BD18', 'Q9FNE4', 'F4JG98', 'Q8GYP3', 'Q9FFP0', 'A0A178UWL0', 'A0A178VM97', 'Q9FHB0', 'F4IXX4', 'Q9ASP6', 'Q9SZI2', 'Q9M086']

In [120]:
# Filter the DataFrame for rows where 'cluster' is 1
filtered_df = df[df[' cluster'] == 3]

# Get the 'UniProt ID' column from the filtered DataFrame and convert it to a list
uniprot_ids_in_cluster_1 = filtered_df[' UniProt ID'].tolist()

#print("\nUniProt IDs for rows where 'cluster' is 1:")
#print(uniprot_ids_in_cluster_1)
new_list = [s.replace(' ', '') for s in uniprot_ids_in_cluster_1]
#print("\t".join(new_list))
print(new_list)

['A0A1P8BBR6', 'Q9C633', 'Q9SZU4', 'Q8LCS6', 'C0Z225', 'O81834', 'Q9STW1', 'Q9LZE2', 'F4KH50', 'Q9ZVU2', 'F4J7B4', 'F4J6D7', 'Q94A40', 'F4J5Z7', 'O49733', 'Q9FLX8', 'Q9SHD0', 'Q94GA6', 'A0A1P8B5V8', 'A0A178WDK9', 'Q38798', 'Q9FG23', 'F4IXU3', 'O64760', 'Q9C813', 'Q9S793', 'Q9LZU7', 'Q9FM29', 'Q9FY67', 'O82491', 'F4IDC2', 'A0A1P8B664', 'A0A1P8ANT8', 'B9DFG3', 'O80668', 'Q9SD55', 'Q9LSH4', 'Q9FML9', 'A0MFS5', 'Q9FF55', 'Q9SJT9', 'A0A1P8APK6', 'F4J4Q8', 'F4J4R5', 'Q9LVA7', 'Q0WRC9', 'F4JGK7', 'Q9SK71', 'F4JSB9', 'A0A1P8BDX4', 'F4HZY1', 'Q67XL4', 'Q8H0V8', 'Q9LEZ1', 'Q93VI4', 'Q9FNY8', 'Q9LES2', 'Q9M082', 'Q9C6G8', 'Q8LPL8', 'Q9LTB9', 'F4I765', 'F4I552']

In [125]:
clus = 1

while clus < 25:
    filtered_df = df[df[' cluster'] == clus]
    filtered_df[' UniProt ID'].to_csv(f"/home/wenyuantong/Desktop/data/arabi_FINCHES_clusters/clust_{clus}.txt", header=None, index=None, sep='\t')
    clus +=1

In [119]:
file_name_csv = "/home/wenyuantong/Desktop/data/arabi_FINCHES_clusters/clust_3.txt"

with open(file_name_csv, 'w') as f:
    f.write(", ".join(new_list))
    #f.write(str(new_list))

print(f"List successfully exported as comma-separated string to '{file_name_csv}'.")

List successfully exported as comma-separated string to '/home/wenyuantong/Desktop/data/arabi_FINCHES_clusters/clust_3.txt'.