In [3]:
import pandas as pd

In [9]:
df1 = pd.read_csv('/home/wenyuantong/Desktop/data/arabi_effector_heterotypic_clusers_mpipi.csv')
display(df1.head())

,index,UniProt ID,name,cluster,idr_start,idr_end,sequence
0,1,A0A1P8AP82,tr|A0A1P8AP82|A0A1P8AP82_ARATH Transmembrane ...,1,1,144,MQIEKFLYIAKSFLMFIRTFPTLTKHKKTTSMASNLLLIVLLVLV...
1,2,F4K9U0,tr|F4K9U0|F4K9U0_ARATH TPX2 (Targeting protei...,1,1,109,MESLTLKNGKAGTPVKDRSKFQSNQKISRSSENANPNISQASPSK...
2,3,Q84JE5,tr|Q84JE5|Q84JE5_ARATH Cytomatrix protein-lik...,1,239,342,STKKDEEISKLTRDLESAKKSRGFTPVLTRCTKLEKRSNGNTVGS...
3,4,F4HRK6,tr|F4HRK6|F4HRK6_ARATH Uncharacterized protei...,1,1,111,MLLMSATLSTHIKVNGNLGLSIYVRKKPASPSQVVETGKKISPLL...
4,5,O23683,tr|O23683|O23683_ARATH At2g42110 OS=Arabidops...,1,1,137,MDLVVITETTIPTKITHVNKKSSDELLRKFADPDDVDESSKSTKR...

In [30]:
df2 = pd.read_csv('/home/wenyuantong/Desktop/data/IDR_arabi_domain.tsv', sep='\t', index_col=None)
df2

       A0A1P8B415    1   66  N-terminal
0      A0A1P8B415  306  525      middle
1          A4FVP2    1   34  N-terminal
2          F4I316    1  292  N-terminal
3          F4I316  415  496      middle
4          F4IB81  191  325      middle
...           ...  ...  ...         ...
23610      Q9SV09  332  540  C-terminal
23611      Q9SVC2    1   49  N-terminal
23612      Q9SVC2  309  341  C-terminal
23613      Q9SZD3    1  115         IDP
23614      Q9XFB0    1  115  N-terminal

[23615 rows x 4 columns]

In [42]:
# Define the substring to search for
substring_to_find = 'Q8GYN5'

# Filter the DataFrame to get rows where 'item_description' contains the substring
# The `case=False` argument makes the search case-insensitive
# The `na=False` argument treats NaN values as not containing the substring
sub_df = df2[df2['A0A1P8B415'].str.contains(substring_to_find, case=False, na=False)]

print(f"\nSub-DataFrame containing '{substring_to_find}' in 'item_description' column:")
display(sub_df)

Sub-DataFrame containing 'Q8GYN5' in 'item_description' column:

     A0A1P8B415  1   66 N-terminal
6177     Q8GYN5  1  211        IDP

In [24]:
#df = pd.read_table('/home/wenyuantong/Desktop/data/IDR_arabi_domain.tsv', index_col=False)
#df

In [34]:
# Define the substring to search for
substring_to_find = 'RIN4'

# Filter the DataFrame to get rows where 'item_description' contains the substring
# The `case=False` argument makes the search case-insensitive
# The `na=False` argument treats NaN values as not containing the substring
sub_df = df1[df1[' name'].str.contains(substring_to_find, case=False, na=False)]

print(f"\nSub-DataFrame containing '{substring_to_find}' in 'item_description' column:")
display(sub_df)

Sub-DataFrame containing 'RIN4' in 'item_description' column:

,index,UniProt ID,name,cluster,idr_start,idr_end,sequence
1874,1875,A0A1P8BGZ5,tr|A0A1P8BGZ5|A0A1P8BGZ5_ARATH RPM1-interacti...,10,1,134,MGKINRCNLNIDLIVLFFFSGNIWFPKQIICLSNEFYSWIQNAAW...

In [38]:
for i in sub_df[' name']:
    print(i)

 tr|A0A1P8BGZ5|A0A1P8BGZ5_ARATH RPM1-interacting protein 4 (RIN4) family protein OS=Arabidopsis thaliana OX=3702 GN=At5g19473 PE=1 SV=1

In [ ]:
# Define the substring to search for
substring_to_find = 'HopM'

# Filter the DataFrame to get rows where 'item_description' contains the substring
# The `case=False` argument makes the search case-insensitive
# The `na=False` argument treats NaN values as not containing the substring
sub_df = df1[df1[' name'].str.contains(substring_to_find, case=False, na=False)]

print(f"\nSub-DataFrame containing '{substring_to_find}' in 'item_description' column:")
display(sub_df)

In [24]:
# Define the substring to search for
substring_to_find = 'HopI1p'

# Filter the DataFrame to get rows where 'item_description' contains the substring
# The `case=False` argument makes the search case-insensitive
# The `na=False` argument treats NaN values as not containing the substring
sub_df = df1[df1[' name'].str.contains(substring_to_find, case=False, na=False)]

print(f"\nSub-DataFrame containing '{substring_to_find}' in 'item_description' column:")
display(sub_df)

Sub-DataFrame containing 'HopI1p' in 'item_description' column:

,index,UniProt ID,name,cluster,idr_start,idr_end,sequence
1267,1268,HopI1p,xx|HopI1p|xxxx,7,178,308,SNGARVRRPTPGPSWRPDGAQQQARPQALPGTRPQACSAPPPKAE...

In [8]:
# Define the substring to search for
substring_to_find = 'Q2HII6'

# Filter the DataFrame to get rows where 'item_description' contains the substring
# The `case=False` argument makes the search case-insensitive
# The `na=False` argument treats NaN values as not containing the substring
sub_df = df1[df1[' name'].str.contains(substring_to_find, case=False, na=False)]

print(f"\nSub-DataFrame containing '{substring_to_find}' in 'item_description' column:")
display(sub_df)

NameError: name 'df1' is not defined

In [7]:
substring_to_find = 'Q2HII6'

sub_df = df[df[' UniProt ID'].str.contains(substring_to_find, case=False, na=False)]

print(f"\nSub-DataFrame containing '{substring_to_find}' in 'item_description' column:")
display(sub_df)

KeyError: ' UniProt ID'

In [4]:
df = pd.read_csv('~/Desktop/data/filtered_IDR_Arabi.csv')
display(df.head())

,IDR ID,FASTA header,IDR start,IDR end,IDR len,Rg (A),Re (A),asphericity,scaling_exponent,prefactor,FCR,NCPR,kappa,fract_negative,fract_positive,fract_aro,fract_pro,fract_polar,fract_ali,sequence
0,tr|A0A1P8B415|A0A1P8B415_ARATH Triglyceride li...,tr|A0A1P8B415|A0A1P8B415_ARATH Triglyceride l...,1,66,66,23.80,55.49,0.404,0.535,7.015,0.273,0.121,0.212,0.076,0.197,0.121,0.076,0.303,0.212,MTSLQLHFSVHFLRPKHRLRYSPIFNTRTFNFPGKITFRLRAKPN...
1,tr|A0A1P8B415|A0A1P8B415_ARATH Triglyceride li...,tr|A0A1P8B415|A0A1P8B415_ARATH Triglyceride l...,306,525,220,47.99,115.33,0.419,0.569,5.882,0.286,-0.095,0.176,0.191,0.095,0.027,0.023,0.395,0.268,APLKNTELLNNTAEDSEGASSEDSSDQHRSTNLSSSGKLSKDKDG...
2,sp|A4FVP2|TPS03_ARATH Terpenoid synthase 3; ch...,sp|A4FVP2|TPS03_ARATH Terpenoid synthase 3; c...,1,34,34,16.55,40.86,0.455,0.568,6.505,0.294,0.235,0.297,0.029,0.265,0.059,0.118,0.382,0.147,MPKRQAQRRFTRKTDSKTPSQPLVSRRSANYQPS
3,sp|F4I316|SUN3_ARATH SUN domain-containing pro...,sp|F4I316|SUN3_ARATH SUN domain-containing pr...,1,292,292,54.52,122.24,0.427,0.552,6.358,0.288,-0.041,0.179,0.164,0.123,0.058,0.027,0.384,0.240,MQRSCRTRRRVSVNKFNGRNSFYKVSLSLVFLLWVLLFFSTLLIS...
4,sp|F4I316|SUN3_ARATH SUN domain-containing pro...,sp|F4I316|SUN3_ARATH SUN domain-containing pr...,415,496,82,28.27,67.04,0.438,0.561,6.196,0.390,-0.049,0.150,0.220,0.171,0.012,0.085,0.317,0.195,DNKNAYKPREGDSEHKEKPMQQIESLEGDDGADKSTHREKEKEAP...

In [10]:
print("Column names of the DataFrame:")
print(df.columns)

Column names of the DataFrame:
Index(['IDR ID', ' FASTA header', ' IDR start', ' IDR end', ' IDR len',
       ' Rg (A)', ' Re (A)', ' asphericity', ' scaling_exponent', ' prefactor',
       ' FCR', ' NCPR', ' kappa', ' fract_negative', ' fract_positive',
       ' fract_aro', ' fract_pro', ' fract_polar', ' fract_ali', ' sequence'],
      dtype='object')

In [5]:
# Define the substring to search for
substring_to_find = 'NPR1'

# Filter the DataFrame to get rows where 'item_description' contains the substring
# The `case=False` argument makes the search case-insensitive
# The `na=False` argument treats NaN values as not containing the substring
sub_df = df[df[' FASTA header'].str.contains(substring_to_find, case=False, na=False)]

print(f"\nSub-DataFrame containing '{substring_to_find}' in 'FASTA header' column:")
display(sub_df)

Sub-DataFrame containing 'NPR1' in 'FASTA header' column:

,IDR ID,FASTA header,IDR start,IDR end,IDR len,Rg (A),Re (A),asphericity,scaling_exponent,prefactor,FCR,NCPR,kappa,fract_negative,fract_positive,fract_aro,fract_pro,fract_polar,fract_ali,sequence
3815,sp|O23530|SNC1_ARATH Protein SUPPRESSOR OF npr...,sp|O23530|SNC1_ARATH Protein SUPPRESSOR OF np...,1353,1437,85,28.80,68.18,0.442,0.563,6.246,0.224,-0.106,0.232,0.165,0.059,0.035,0.047,0.388,0.294,ENNQQTTRSEKRMRMTSGTSEEDINLPYGLIVADTGLAALNMELS...
15482,sp|P93002|NPR1_ARATH Regulatory protein NPR1 O...,sp|P93002|NPR1_ARATH Regulatory protein NPR1 ...,557,593,37,16.02,36.90,0.409,0.499,6.301,0.324,0.108,0.524,0.108,0.216,0.000,0.000,0.568,0.108,SEDNLELGNSSLTDSTSSTSKSTGGKRSNRKLSHRRR
22783,sp|D7SFH9|LRL26_ARATH Protein SUPPRESSOR OF NP...,sp|D7SFH9|LRL26_ARATH Protein SUPPRESSOR OF N...,1,39,39,17.01,41.44,0.440,0.554,6.360,0.103,0.051,0.488,0.026,0.077,0.026,0.000,0.487,0.359,MNSQQSTRTKQMLQQSSTHLLCGVVLLQLFAAQVDAQRS
22784,sp|D7SFH9|LRL26_ARATH Protein SUPPRESSOR OF NP...,sp|D7SFH9|LRL26_ARATH Protein SUPPRESSOR OF N...,690,751,62,25.58,61.15,0.451,0.571,6.908,0.145,0.016,0.477,0.065,0.081,0.032,0.177,0.339,0.306,GGVLTLISTSSLPPAQDPNPIFTHDDVTEPPLPPVIAKSPTSTLG...
22785,sp|D7SFH9|LRL26_ARATH Protein SUPPRESSOR OF NP...,sp|D7SFH9|LRL26_ARATH Protein SUPPRESSOR OF N...,1085,1118,34,17.16,42.67,0.450,0.599,6.456,0.176,-0.118,0.279,0.147,0.029,0.029,0.118,0.324,0.353,ALEVPPRPVLQQIPISNLHESSILSEDVSVYTEG

In [6]:
name_list = sub_df[' FASTA header'].tolist()
print(name_list)

[' sp|O23530|SNC1_ARATH Protein SUPPRESSOR OF npr1-1; CONSTITUTIVE 1 OS=Arabidopsis thaliana OX=3702 GN=SNC1 PE=1 SV=5', ' sp|P93002|NPR1_ARATH Regulatory protein NPR1 OS=Arabidopsis thaliana OX=3702 GN=NPR1 PE=1 SV=1', ' sp|D7SFH9|LRL26_ARATH Protein SUPPRESSOR OF NPR1-1 CONSTITUTIVE 4 OS=Arabidopsis thaliana OX=3702 GN=LRK10L-2.6 PE=1 SV=1', ' sp|D7SFH9|LRL26_ARATH Protein SUPPRESSOR OF NPR1-1 CONSTITUTIVE 4 OS=Arabidopsis thaliana OX=3702 GN=LRK10L-2.6 PE=1 SV=1', ' sp|D7SFH9|LRL26_ARATH Protein SUPPRESSOR OF NPR1-1 CONSTITUTIVE 4 OS=Arabidopsis thaliana OX=3702 GN=LRK10L-2.6 PE=1 SV=1']

In [30]:
# Filter the DataFrame for rows where 'cluster' is 1
filtered_df = df1[df1[' cluster'] == 7]

# Get the 'UniProt ID' column from the filtered DataFrame and convert it to a list
uniprot_ids_in_cluster_1 = filtered_df[' UniProt ID'].tolist()

print("\nUniProt IDs for rows where 'cluster' is 7:")
print(uniprot_ids_in_cluster_1)

UniProt IDs for rows where 'cluster' is 7:
[' HopI1e', ' HopI1p', ' HopAB1i', ' HopAU1a', ' HopM1n', ' HopR1d', ' Q8LAF9', ' Q9FG24', ' F4JKN4', ' Q0WTB4', ' O80757', ' Q6NLF1', ' Q8H0W3', ' A0A1P8B3W6', ' A8MSD1', ' Q84WP3', ' A0A1P8B1Q0', ' Q8GX78', ' O64827', ' Q8RXK8', ' Q9LJI2', ' B3H7M7', ' Q94BY9', ' Q9M102', ' Q9SXJ7', ' Q56XJ7', ' Q08A72', ' Q9FHD8', ' O80988', ' Q1G3K6', ' Q6AWW4', ' F4KFU8', ' Q0WX00', ' O80571', ' Q5XVC1', ' Q9ZUY1', ' Q9M2U4', ' Q9M896', ' Q0WQA4', ' Q9LDP7', ' F4IEH1', ' F4K946', ' P0CB25', ' Q9LQN3', ' P92522', ' Q9FMT4', ' Q9FIV6', ' Q9LFR0', ' Q93Z91', ' Q9M8K3', ' B3H707', ' A0A1P8ANJ1', ' Q8S8L6', ' Q9MAP1', ' O22227', ' Q9ZPV3', ' Q94EH8', ' Q9ZQB9', ' F4KDF5', ' Q9SK51', ' Q9SZG3', ' Q9CA69', ' F4IQ85', ' Q56Y48', ' Q8GYA5', ' Q9LS00', ' A0A1I9LPY2', ' Q93XX2', ' Q9LVE9', ' A0A1P8BDX7', ' Q3E9N0', ' A0A178UN75', ' Q8VZ11', ' P92540', ' P93287', ' Q8L5T5', ' Q700C7', ' Q9ZT96', ' Q949R3', ' A0A1P8AT89', ' F4I1X2', ' Q8GWA9', ' Q9FK56', ' A0A1P8B8R8', ' Q8GZ79', ' F4J9G6', ' Q9S7I8', ' O49696', ' Q8S8G6', ' A8MQ81', ' O64884', ' B9DGJ0', ' Q94A56', ' Q9FKW0', ' Q9LYN6', ' A0A1P8AT27', ' Q9ZT92', ' A0A1P8B6G5', ' Q9LSZ4', ' Q56XP9', ' Q9FJW2', ' A0A1P8B9B9', ' P94088', ' Q8VZC0', ' Q9FW03', ' Q8L925', ' Q9SKW7', ' P43254', ' Q9FK63', ' Q8L836', ' Q9SY21', ' P0C5K4', ' Q3E9Y5', ' Q9LFT3', ' Q9SSQ7', ' B3H6Q9', ' F4IQV7', ' Q9FRH4', ' F4JJD6', ' Q84R26', ' Q5XEN2', ' Q8W571', ' A8MQS5', ' Q84WG3', ' Q9LY96', ' A0A1P8B2D2', ' Q93VI9', ' Q9LV97', ' Q94A38', ' O82389', ' O65567', ' Q9ZQF5', ' F4HVZ8', ' Q9SY69', ' Q9LTI0', ' Q9C8J2', ' F4KFX1', ' Q9C8C9', ' Q5XUY2', ' Q66GS2', ' Q3E9I4', ' Q8GWE0', ' F4JWS5', ' Q56X46', ' A0A1P8APN6', ' Q8S8A8', ' Q9FKN6', ' P92534', ' O22779', ' Q9ZSI7', ' F4K2V9', ' Q93ZF7', ' F4JDS7', ' P92563', ' Q9SD44', ' Q9C5P4', ' F4JUP8', ' Q9LJX6', ' Q9XI04', ' Q8LAL0', ' O81000', ' Q8L3X8', ' Q6AWX1', ' Q1PDV2', ' O81011', ' Q9LVM1', ' Q9ZQZ9', ' F4JCC1', ' F4JSH1', ' Q9FG30', ' Q9M9L8', ' Q9ZUZ2', ' O64492', ' F4IWK7', ' A0A1I9LT67', ' Q9C6J3', ' Q8W4A5', ' F4KFC7', ' Q93YW7', ' Q9LQ19', ' Q9LSB1', ' Q9FIL7', ' A0A1I9LSM5', ' F4J1H7', ' Q84WU8', ' F4K2D7', ' Q3E9A8', ' Q1PDZ0', ' F4J6R3', ' P93309', ' Q8S8T7', ' Q8L7S8', ' Q9STJ8', ' A8MR87', ' F4JNB3', ' Q9FX67', ' Q5S2C4', ' F4J6I7', ' Q56X76', ' Q9SVK9', ' P92552', ' P92565', ' Q9SIS3', ' Q5RJC7', ' Q8VYF9', ' Q9FGG8', ' Q9SV96', ' Q56W16', ' Q9FMW3', ' A0A1I9LQ26', ' Q9C902', ' Q5EAE9', ' Q9LPY3', ' B9DHA5', ' Q8L733', ' Q8W464', ' O04319', ' F4I1E4', ' F4JZW1', ' Q93YP7', ' F4IRH5', ' F4IWG7', ' F4K2L8', ' F4HXC5', ' O80832', ' O80952', ' Q9SU55', ' Q9ZPV4', ' F4I792', ' Q8L908', ' Q9SVR9', ' A0A1P8AWH6', ' Q3EB86', ' Q8VZI8', ' Q9FKR9', ' Q9FI02', ' Q8GW46', ' Q9FZE4', ' Q3E8M6', ' Q9SGN5', ' Q9SKJ6', ' Q9SZA4', ' A0A178WIZ5', ' A0A1I9LN39', ' Q6NPR6', ' Q8VY06', ' Q9FFS4', ' Q0WM29', ' Q1G3B3', ' Q8VY68']

In [34]:
# Filter the DataFrame for rows where 'cluster' is 1
filtered_df = df1[df1[' cluster'] == 24]

# Get the 'UniProt ID' column from the filtered DataFrame and convert it to a list
uniprot_ids_in_cluster_1 = filtered_df[' UniProt ID'].str.replace(' ', '').tolist()

print("\nUniProt IDs for rows where 'cluster' is 24:")
print(uniprot_ids_in_cluster_1)

UniProt IDs for rows where 'cluster' is 24:
['Q0WVH7', 'Q7XA71', 'A0A1I9LQY7', 'Q9LVG1', 'Q9LST3', 'Q9FKW0', 'A0A1P8BD18', 'Q9FNE4', 'F4JG98', 'Q8GYP3', 'Q9FFP0', 'A0A178UWL0', 'A0A178VM97', 'Q9FHB0', 'F4IXX4', 'Q9ASP6', 'Q9SZI2', 'Q9M086']

In [36]:
uniprot_ids_in_cluster_1 = filtered_df[' UniProt ID'].str.replace(' ', '')
uniprot_ids_in_cluster_1.to_csv(f"/home/wenyuantong/Desktop/data/arabi_effector_24_clust.txt", header=None, index=None, sep='\t')