In [1]:
import numpy as np
import matplotlib

import matplotlib.pyplot as plt
from matplotlib.pyplot import figure

import pandas as pd

import re

In [2]:
#load in just the Arabidopsis Data set
df3 = pd.read_csv("/home/wenyuantong/Desktop/data/arabi_cross/100_150.csv", index_col=0)
df3.head()

,F4IB81_middle_191_325,Q0WP38_N-terminal_1_127,Q7XA66_C-terminal_93_242,Q8LAF9_N-terminal_1_113,Q940Y9_N-terminal_1_126,Q9C5H4_middle_131_261,Q9LNP6_C-terminal_213_328,Q9LUZ5_N-terminal_1_100,Q9LUZ5_middle_517_622,Q9SCU5_C-terminal_406_549,...,Q9C9J1_N-terminal_1_100,Q9CAV6_middle_290_393,Q9FMK8_IDP_1_138,Q9M0V4_N-terminal_1_131,Q9M158_N-terminal_1_104,F4I4Q1_C-terminal_188_303,Q6NN00_IDP_1_116,Q8VY68_IDP_1_113,Q9SZD3_IDP_1_115,Q9XFB0_N-terminal_1_115
F4IB81_middle_191_325,2.173744,4.955565,2.731385,1.004872,1.413445,2.018600,0.547160,2.448571,1.671656,0.792111,...,2.247709,-1.459587,2.059876,4.283379,2.857878,6.205853,3.050188,1.032668,1.311511,1.793946
Q0WP38_N-terminal_1_127,5.267727,15.548567,2.460256,0.243044,0.598914,3.479011,1.330661,6.113140,-5.940918,5.057411,...,1.999173,3.590195,0.562825,12.914173,4.733822,18.148154,8.185653,-0.061797,3.231808,1.948292
Q7XA66_C-terminal_93_242,2.458247,2.083016,4.102955,2.436277,3.095957,2.333399,1.293153,1.826779,5.169203,0.368553,...,3.267093,-2.266097,3.505828,1.571661,2.880411,2.355006,2.408988,2.570691,1.762559,3.112770
Q8LAF9_N-terminal_1_113,1.200511,0.273156,3.233996,1.537261,2.463209,0.900981,0.404432,0.918357,5.972982,-0.803547,...,2.594724,-3.640606,3.084627,0.200220,1.841420,0.710283,0.784952,1.659385,-0.169089,2.587987
Q940Y9_N-terminal_1_126,1.514405,0.603668,3.685663,2.209068,2.495591,1.997687,0.774155,1.172006,5.608511,-0.442412,...,2.929752,-3.110195,3.314959,0.858460,2.453430,1.005241,1.343525,2.286190,1.284145,2.456314

In [3]:
#load in file that stores cluster info
df2 = pd.read_csv('/home/wenyuantong/Desktop/data/arabi_heterotypic_clusers_mpipi.csv')
display(df2.head())

,index,UniProt ID,name,cluster,idr_start,idr_end,sequence
0,1,Q0WVH7,tr|Q0WVH7|Q0WVH7_ARATH Protein SDA1 OS=Arabid...,1,510,651,VFSNVPNVELLQESDNESGSDGDQDDDGVELPIGDDVEQELIPGD...
1,2,Q7XA71,tr|Q7XA71|Q7XA71_ARATH At2g22080 OS=Arabidops...,1,50,177,DVIENGYEVVDAVEGNGNNDDSGDDGGEDEEGSADDAEGKETKKG...
2,3,A0A1I9LQY7,tr|A0A1I9LQY7|A0A1I9LQY7_ARATH N-lysine methy...,1,156,293,NVDSDSFGIKEYLAAKSLIASRSFEIDDYHGSGMVPLADLFNHKT...
3,4,Q9LVG1,sp|Q9LVG1|Y5013_ARATH B3 domain-containing pr...,1,118,230,RSSDQSEEIKVESDSDEQNQASDDVLSLDEDDDDSDYNCGEDNDS...
4,5,Q9LST3,sp|Q9LST3|Y5142_ARATH B3 domain-containing pr...,1,123,245,LDDNDDGFNDDQDYGEEVKSSENFIVLDDDDISDVQDYNEEDTSS...

In [5]:
#create a new empty df with the row names of all Arabidopsis IDRs
df = pd.DataFrame(index=df3.index)
df.head()

Empty DataFrame
Columns: []
Index: [F4IB81_middle_191_325, Q0WP38_N-terminal_1_127, Q7XA66_C-terminal_93_242, Q8LAF9_N-terminal_1_113, Q940Y9_N-terminal_1_126]

In [30]:
#get mean of each cluster: get a sub-df of only that cluster, average that sub-df and add it to new df, columns are cluster number (1-24)
df = pd.DataFrame(index=df3.index)
i = 1


for i in range(1,25):
    #print(i)

    filtered_df = df2[df2[' cluster'] == i]
    unique_names = filtered_df[' UniProt ID'].unique()
    unique_names = [s.replace(' ', '') for s in unique_names]

    search_pattern = '|'.join([re.escape(s) for s in unique_names])

    # Identify rows to drop based on partial match
    rows_to_keep = df3.index[df3.index.str.contains(search_pattern, case=False, regex=True)].tolist()

    mask = df3.index.isin(rows_to_keep)

    df_filtered = df3[mask]
    
    column_means = df_filtered.mean()
    mean_df = column_means.to_frame(name=f'{i}')
    #print("\nMean of each column:")
    #column_means
    #df[f'{i}'] = column_means
    df = df.join(mean_df)

In [27]:
df.shape

(3740, 24)

In [28]:
df

,1,2,3,4,5,6,7,8,9,10,...,15,16,17,18,19,20,21,22,23,24
F4IB81_middle_191_325,5.508768,6.273087,4.457287,2.510511,4.169673,3.535628,5.293152,6.210874,8.651433,4.651189,...,3.921564,3.034199,4.814851,4.352708,5.598636,1.425004,2.450722,0.379268,-0.861064,-2.354631
Q0WP38_N-terminal_1_127,23.649970,15.338645,16.932743,10.240368,12.936718,8.336808,10.977301,9.076671,-6.332267,-0.035962,...,3.179717,3.682506,8.151619,6.203848,4.878148,6.336819,4.746380,1.793272,2.787594,-1.829152
Q7XA66_C-terminal_93_242,-1.046052,3.747047,0.498455,0.697074,1.920507,2.972440,4.325582,6.341782,15.981298,7.854877,...,5.637094,4.264707,4.799268,4.961111,7.162739,0.831327,2.980469,1.388817,-0.985846,-1.130065
Q8LAF9_N-terminal_1_113,-3.289845,1.163425,-1.648547,-1.058333,-0.210313,0.956885,1.919075,3.617632,13.314278,5.795249,...,3.562393,2.378033,2.468956,2.725138,4.704323,-0.674566,1.219102,0.127739,-2.035441,-1.717771
Q940Y9_N-terminal_1_126,-2.834009,1.946424,-1.161672,-0.641686,0.325823,1.592740,2.676446,4.766574,14.838945,6.859071,...,4.487307,3.109761,3.364430,3.662671,5.870069,-0.274476,1.840197,0.502602,-1.656218,-1.504057
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
F4I4Q1_C-terminal_188_303,28.222525,17.656207,20.256935,12.606077,15.379064,9.888792,12.568312,9.909276,-10.453570,-1.059253,...,3.289244,4.241994,9.212807,6.942002,4.828744,8.135945,5.792548,2.836888,4.558703,-0.673772
Q6NN00_IDP_1_116,10.870837,9.009365,8.246330,4.968791,6.840055,5.099348,7.056185,7.227623,4.319666,3.361902,...,3.837042,3.348881,5.935215,5.063350,5.523222,3.056142,3.285274,0.906921,0.586154,-1.901723
Q8VY68_IDP_1_113,-3.642420,1.072554,-1.824105,-1.092512,-0.317034,0.983805,1.901328,3.744309,13.794609,6.024353,...,3.712453,2.481685,2.533717,2.837239,4.888435,-0.617659,1.308352,0.230370,-1.816102,-1.450157
Q9SZD3_IDP_1_115,2.602404,4.250434,2.248097,0.966128,2.334338,2.157882,3.706571,4.713651,9.938156,4.261979,...,3.030382,2.090757,3.410172,3.106496,4.535490,0.244571,1.399862,-0.398254,-1.721093,-2.650727
Q9XFB0_N-terminal_1_115,-0.651212,2.925371,0.342327,0.339792,1.395405,2.171144,3.290034,4.899712,12.912387,6.328615,...,4.391836,3.223757,3.694079,3.821495,5.678264,0.410048,2.161271,0.849362,-1.150512,-1.229365

In [10]:
#load in data of Arabidopsis x effector epsilon values
df1 = pd.read_csv("/home/wenyuantong/Desktop/data/all_cross/100_150.csv", index_col=0)
df1.head()

,AvrRpm1d_N-terminal_1_100,HopD1d_Middle_89_209,HopB1a_N-terminal_1_121,HopB1d_N-terminal_1_131,HopB1b_N-terminal_1_139,HopI1e_Middle_180_300,HopI1g_Middle_142_284,HopI1p_C-terminal_178_308,HopZ1g_C-terminal_245_369,HopZ1a_C-terminal_240_369,...,Q9C9J1_N-terminal_1_100,Q9CAV6_middle_290_393,Q9FMK8_IDP_1_138,Q9M0V4_N-terminal_1_131,Q9M158_N-terminal_1_104,F4I4Q1_C-terminal_188_303,Q6NN00_IDP_1_116,Q8VY68_IDP_1_113,Q9SZD3_IDP_1_115,Q9XFB0_N-terminal_1_115
AvrRpm1d_N-terminal_1_100,-0.099344,2.769858,1.569711,1.718177,1.682605,-0.565022,0.171453,-1.205824,0.995338,0.868050,...,1.471207,-2.791783,1.016437,2.803725,1.746812,4.885748,2.087629,0.177777,-0.218062,1.326654
HopD1d_Middle_89_209,2.289139,5.603817,4.071223,4.443782,4.495035,2.703572,3.613500,0.807081,3.493468,3.420389,...,3.430690,0.207167,3.508847,6.737833,4.298970,8.806285,5.179671,2.089448,2.536955,3.284435
HopB1a_N-terminal_1_121,1.297282,4.071223,4.004781,4.208163,4.216939,2.549349,4.249926,3.147091,2.427721,2.568907,...,3.583359,-2.013979,3.940108,2.298073,3.288255,3.123128,3.100269,2.826260,2.080635,3.482781
HopB1d_N-terminal_1_131,1.311585,4.104562,3.886929,4.140291,4.220488,2.382784,4.020923,2.897896,2.382539,2.519340,...,3.613476,-1.869420,3.902919,2.564550,3.316586,3.436947,3.190328,2.601665,1.893498,3.488811
HopB1b_N-terminal_1_139,1.210507,3.912944,3.670860,3.977582,4.012160,2.081966,3.704552,2.727727,2.370420,2.469503,...,3.342640,-2.018386,3.748561,2.704256,3.092018,3.604549,2.770685,2.297429,1.275843,3.274173

In [11]:
#load in all the effector names
df_psy = pd.read_csv('/home/wenyuantong/Desktop/data/IDR_psytec_domain.tsv', sep='\t', header=None)
df_psy[0] = df_psy[0].str.replace(' ', '')
df_psy.head()

        0    1    2           3
0  HopX1a    1   88  N-terminal
1  HopX1a  200  247      Middle
2  HopX1a  298  380  C-terminal
3  HopX1c    1   87  N-terminal
4  HopX1c  212  267      Middle

In [12]:
#keep only the effectors (rows) x Arabidopsis (columns) in df1
unique_names = df_psy[0].unique()

search_pattern = '|'.join([re.escape(s) for s in unique_names])

# Identify columns to drop based on partial match
columns_to_drop_partial = df1.columns[df1.columns.str.contains(search_pattern, case=False, regex=True)].tolist()

df_temp_partial = df1.drop(columns=columns_to_drop_partial)

rows_to_keep = df1.index[df1.index.str.contains(search_pattern, case=False, regex=True)].tolist()

mask = df1.index.isin(rows_to_keep)

df_filtered1 = df_temp_partial[mask]

df_filtered1

,F4IB81_middle_191_325,Q0WP38_N-terminal_1_127,Q7XA66_C-terminal_93_242,Q8LAF9_N-terminal_1_113,Q940Y9_N-terminal_1_126,Q9C5H4_middle_131_261,Q9LNP6_C-terminal_213_328,Q9LUZ5_N-terminal_1_100,Q9LUZ5_middle_517_622,Q9SCU5_C-terminal_406_549,...,Q9C9J1_N-terminal_1_100,Q9CAV6_middle_290_393,Q9FMK8_IDP_1_138,Q9M0V4_N-terminal_1_131,Q9M158_N-terminal_1_104,F4I4Q1_C-terminal_188_303,Q6NN00_IDP_1_116,Q8VY68_IDP_1_113,Q9SZD3_IDP_1_115,Q9XFB0_N-terminal_1_115
AvrRpm1d_N-terminal_1_100,1.240492,3.737950,1.659949,0.119882,0.756195,0.347234,-0.576192,1.549778,1.636852,-0.488003,...,1.471207,-2.791783,1.016437,2.803725,1.746812,4.885748,2.087629,0.177777,-0.218062,1.326654
HopD1d_Middle_89_209,4.098459,7.579678,4.465464,2.196519,2.713931,3.579115,1.989472,3.951530,2.198687,2.973213,...,3.430690,0.207167,3.508847,6.737833,4.298970,8.806285,5.179671,2.089448,2.536955,3.284435
HopB1a_N-terminal_1_121,3.029270,2.737557,4.551335,2.579969,3.452459,2.593104,1.572155,2.230994,5.391103,0.869289,...,3.583359,-2.013979,3.940108,2.298073,3.288255,3.123128,3.100269,2.826260,2.080635,3.482781
HopB1d_N-terminal_1_131,3.005351,2.983603,4.520187,2.473020,3.406969,2.545499,1.532871,2.290488,5.176262,0.961678,...,3.613476,-1.869420,3.902919,2.564550,3.316586,3.436947,3.190328,2.601665,1.893498,3.488811
HopB1b_N-terminal_1_139,2.693322,3.006586,4.291742,2.253916,3.161529,2.306857,1.355773,2.262313,5.221079,0.967206,...,3.342640,-2.018386,3.748561,2.704256,3.092018,3.604549,2.770685,2.297429,1.275843,3.274173
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
HopR1d_C-terminal_1216_1324,0.142605,-2.023899,2.429905,1.112799,1.959495,0.073586,-0.476375,-0.279583,6.326717,-2.376009,...,2.130824,-5.078364,2.422905,-1.980024,1.100744,-1.856240,-0.297821,1.415451,-0.610059,1.834882
HopW1g_C-terminal_674_774,3.561768,3.671612,5.136468,3.024337,3.838733,3.268485,1.991844,2.856696,5.584795,1.661532,...,3.895273,-1.393249,4.460027,3.393506,3.754851,4.241621,3.586456,3.220607,2.577398,3.704579
HopW1s_C-terminal_791_905,2.635738,2.141844,4.937984,3.064266,3.358044,3.248261,1.905123,2.264623,6.111671,1.052195,...,3.615584,-1.859873,4.525307,2.608501,3.397860,2.658888,2.222153,3.164387,2.307306,3.283622
HopY1e_Middle_106_220,2.839947,3.947453,3.705045,1.848197,2.595684,2.137060,0.998701,2.424003,3.565695,0.808835,...,2.961513,-1.851439,2.892109,3.262315,3.034607,4.780330,3.367616,2.086262,1.941306,2.779143
HopZ1h_C-terminal_247_369,1.556686,3.897091,2.174765,0.917561,0.941225,1.178949,0.106508,1.841808,1.575101,0.083268,...,1.762902,-2.033109,1.305553,3.296288,2.068654,4.908505,2.161530,0.845153,0.954436,1.662640

In [13]:
#transpose to get effectors (rows) x Arabidopsis (columns)
df_transposed = df_filtered1.T
df_transposed

,AvrRpm1d_N-terminal_1_100,HopD1d_Middle_89_209,HopB1a_N-terminal_1_121,HopB1d_N-terminal_1_131,HopB1b_N-terminal_1_139,HopI1e_Middle_180_300,HopI1g_Middle_142_284,HopI1p_C-terminal_178_308,HopZ1g_C-terminal_245_369,HopZ1a_C-terminal_240_369,...,HopAZ1s_IDP_1_145,HopB1e_N-terminal_1_118,HopBR1a_IDP_1_133,HopD1f_N-terminal_1_103,HopO1g_N-terminal_1_146,HopR1d_C-terminal_1216_1324,HopW1g_C-terminal_674_774,HopW1s_C-terminal_791_905,HopY1e_Middle_106_220,HopZ1h_C-terminal_247_369
F4IB81_middle_191_325,1.240492,4.098459,3.029270,3.005351,2.693322,1.712272,2.357585,-0.119294,1.897989,1.732440,...,2.642865,2.805536,1.081749,3.680766,3.420079,0.142605,3.561768,2.635738,2.839947,1.556686
Q0WP38_N-terminal_1_127,3.737950,7.579678,2.737557,2.983603,3.006586,0.322971,-0.743368,-5.832922,4.605672,3.877879,...,1.818045,2.375985,0.953943,5.718647,0.958939,-2.023899,3.671612,2.141844,3.947453,3.897091
Q7XA66_C-terminal_93_242,1.659949,4.465464,4.551335,4.520187,4.291742,2.762153,4.166711,3.244225,2.378808,2.447846,...,4.418353,4.565711,3.078096,4.610492,5.545310,2.429905,5.136468,4.937984,3.705045,2.174765
Q8LAF9_N-terminal_1_113,0.119882,2.196519,2.579969,2.473020,2.253916,1.105126,2.304702,2.424459,1.024564,1.089443,...,2.723318,2.685012,1.699022,2.438361,3.301208,1.112799,3.024337,3.064266,1.848197,0.917561
Q940Y9_N-terminal_1_126,0.756195,2.713931,3.452459,3.406969,3.161529,2.560660,3.957414,3.084575,1.062702,1.206503,...,3.351595,3.460327,1.876693,3.037903,4.793377,1.959495,3.838733,3.358044,2.595684,0.941225
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
F4I4Q1_C-terminal_188_303,4.885748,8.806285,3.123128,3.436947,3.604549,0.691219,-0.872908,-6.516300,5.681567,4.857592,...,2.125522,2.805408,1.615125,6.620065,0.840939,-1.856240,4.241621,2.658888,4.780330,4.908505
Q6NN00_IDP_1_116,2.087629,5.179671,3.100269,3.190328,2.770685,2.361919,2.354447,-1.380221,2.600050,2.259507,...,2.506295,2.679305,0.865727,4.343105,3.213551,-0.297821,3.586456,2.222153,3.367616,2.161530
Q8VY68_IDP_1_113,0.177777,2.089448,2.826260,2.601665,2.297429,1.817706,2.957304,2.840613,0.944610,1.032678,...,2.955371,2.808467,1.731414,2.340072,3.673619,1.415451,3.220607,3.164387,2.086262,0.845153
Q9SZD3_IDP_1_115,-0.218062,2.536955,2.080635,1.893498,1.275843,1.312346,1.787420,0.246058,1.216789,1.005895,...,2.217665,1.835158,0.617167,2.156940,2.307694,-0.610059,2.577398,2.307306,1.941306,0.954436
Q9XFB0_N-terminal_1_115,1.326654,3.284435,3.482781,3.488811,3.274173,2.185069,3.447026,2.720278,1.811449,1.874132,...,3.238328,3.505804,1.986710,3.494622,4.334230,1.834882,3.704579,3.283622,2.779143,1.662640

In [14]:
#clean the column and row names of any spaces
df.index = df.index.str.replace(' ', '')
df_transposed.columns = df_transposed.columns.str.replace(' ', '')
df_transposed.index = df_transposed.index.str.replace(' ', '')

In [15]:
#check length of both dfs
print(len(df_transposed))
print(len(df))

3740
3740

In [16]:
from sklearn.metrics.pairwise import cosine_similarity

In [43]:
# The rows will be columns from df1, and columns will be columns from df2
cosine_similarity_df = pd.DataFrame(index=df1_aligned.columns, columns=df2_aligned.columns)
cosine_similarity_df

,1,2,3,4,5,6,7,8,9,10,...,15,16,17,18,19,20,21,22,23,24
AvrRpm1d_N-terminal_1_100,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
HopD1d_Middle_89_209,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
HopB1a_N-terminal_1_121,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
HopB1d_N-terminal_1_131,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
HopB1b_N-terminal_1_139,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
HopR1d_C-terminal_1216_1324,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
HopW1g_C-terminal_674_774,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
HopW1s_C-terminal_791_905,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
HopY1e_Middle_106_220,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
HopZ1h_C-terminal_247_369,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [44]:
# Ensure both DataFrames have the same number of rows
# and align them by the minimum number of rows
min_rows = min(len(df_transposed), len(df))

shared_idx = df_transposed.index.intersection(df.index)

df1_aligned = df_transposed.loc[shared_idx]
df2_aligned = df.loc[shared_idx]


# Initialize a DataFrame to store cosine similarities
# The rows will be columns from df1, and columns will be columns from df2
cosine_similarity_df = pd.DataFrame(index=df1_aligned.columns, columns=df2_aligned.columns)

# Calculate cosine similarity for each column pair
for col1 in df1_aligned.columns:
    for col2 in df2_aligned.columns:
        # Reshape to 2D array if necessary for cosine_similarity function (expects (n_samples, n_features))
        # Here, each column is a 'feature vector', so we transpose it to be a (1, n_features) array.
        vec1 = df1_aligned[col1].values.reshape(1, -1)
        vec2 = df2_aligned[col2].values.reshape(1, -1)

        similarity = cosine_similarity(vec1, vec2)[0][0]
        cosine_similarity_df.loc[col1, col2] = similarity


display(cosine_similarity_df)

,1,2,3,4,5,6,7,8,9,10,...,15,16,17,18,19,20,21,22,23,24
AvrRpm1d_N-terminal_1_100,0.557225,0.750146,0.656865,0.780628,0.761397,0.882644,0.821564,0.818897,0.427424,0.639226,...,0.814488,0.890176,0.85794,0.869501,0.783255,0.906632,0.954744,0.938565,0.669044,0.194375
HopD1d_Middle_89_209,0.67126,0.91399,0.763558,0.820464,0.872839,0.975529,0.974767,0.990335,0.559482,0.735228,...,0.908296,0.947977,0.997771,0.990686,0.931588,0.853536,0.978337,0.717561,0.309682,-0.269498
HopB1a_N-terminal_1_121,0.297181,0.654036,0.42319,0.530066,0.588059,0.800593,0.787376,0.898484,0.818669,0.936931,...,0.993898,0.992307,0.888899,0.947044,0.972973,0.651026,0.935699,0.82005,0.232045,-0.048066
HopB1d_N-terminal_1_131,0.321067,0.672796,0.445758,0.550508,0.608211,0.815362,0.802556,0.908398,0.807064,0.929671,...,0.994009,0.99508,0.899966,0.954573,0.975369,0.66721,0.943542,0.819524,0.239413,-0.059901
HopB1b_N-terminal_1_139,0.316572,0.664703,0.441843,0.551405,0.604073,0.812243,0.795051,0.898974,0.79711,0.923541,...,0.989244,0.993399,0.893077,0.948674,0.96682,0.674648,0.944897,0.837802,0.266666,-0.027918
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
HopR1d_C-terminal_1216_1324,-0.381177,-0.063036,-0.258748,-0.084305,-0.094974,0.182103,0.115247,0.287647,0.712272,0.73333,...,0.623234,0.597009,0.283144,0.413009,0.514882,0.164278,0.478583,0.770377,0.296759,0.584978
HopW1g_C-terminal_674_774,0.360043,0.708056,0.481445,0.575849,0.640187,0.837222,0.831303,0.931721,0.800212,0.923579,...,0.996379,0.997032,0.921454,0.969309,0.986421,0.676839,0.948651,0.789905,0.209632,-0.122099
HopW1s_C-terminal_791_905,0.234985,0.605111,0.36377,0.473373,0.534397,0.759131,0.747314,0.871763,0.848641,0.951449,...,0.989558,0.98044,0.858024,0.924351,0.963726,0.600874,0.909311,0.808003,0.195744,-0.034844
HopY1e_Middle_106_220,0.468374,0.771781,0.583977,0.684271,0.726526,0.896787,0.876525,0.940941,0.693922,0.852294,...,0.968817,0.994958,0.945988,0.978095,0.957518,0.785995,0.986294,0.846126,0.354753,-0.061055
HopZ1h_C-terminal_247_369,0.582373,0.812011,0.685944,0.793184,0.801264,0.930176,0.889102,0.90222,0.518658,0.716645,...,0.8855,0.946193,0.928873,0.939952,0.86932,0.896119,0.991136,0.895086,0.54469,0.044449

In [42]:
file_name = '/home/wenyuantong/Downloads/Updated_cosine_effectorxArabidopsis.xlsx'
cosine_similarity_df.to_excel(file_name, index=True)