In [1]:
import pandas as pd

import numpy as np

In [2]:

# Replace 'your_file.csv' with the actual path to your CSV file
csv_file_path = '/home/wenyuantong/Desktop/data/arabi_IDR_location.csv'

try:
    # Read the CSV file into a DataFrame
    merged_df = pd.read_csv(csv_file_path)

    print(f"Successfully loaded '{csv_file_path}' into a DataFrame.")
    # Display the first 5 rows of the DataFrame
    display(merged_df.head())

except FileNotFoundError:
    print(f"Error: The file '{csv_file_path}' was not found.")
except Exception as e:
    print(f"An error occurred while reading the CSV file: {e}")

Successfully loaded '/home/wenyuantong/Desktop/data/arabi_IDR_location.csv' into a DataFrame.

,Unnamed: 0,IDR ID,FASTA header,IDR start,IDR end,IDR len,Rg (A),Re (A),asphericity,scaling_exponent,...,fract_negative,fract_positive,fract_aro,fract_pro,fract_polar,fract_ali,sequence,Sequence_protein,Sequence Length,location
0,0,tr|A0A1P8B415|A0A1P8B415_ARATH Triglyceride li...,tr|A0A1P8B415|A0A1P8B415_ARATH Triglyceride li...,1,66,66,23.80,55.49,0.404,0.535,...,0.076,0.197,0.121,0.076,0.303,0.212,MTSLQLHFSVHFLRPKHRLRYSPIFNTRTFNFPGKITFRLRAKPN...,MTSLQLHFSVHFLRPKHRLRYSPIFNTRTFNFPGKITFRLRAKPNS...,854,N-terminal
1,1,tr|A0A1P8B415|A0A1P8B415_ARATH Triglyceride li...,tr|A0A1P8B415|A0A1P8B415_ARATH Triglyceride li...,306,525,220,47.99,115.33,0.419,0.569,...,0.191,0.095,0.027,0.023,0.395,0.268,APLKNTELLNNTAEDSEGASSEDSSDQHRSTNLSSSGKLSKDKDG...,MTSLQLHFSVHFLRPKHRLRYSPIFNTRTFNFPGKITFRLRAKPNS...,854,middle
2,2,sp|A4FVP2|TPS03_ARATH Terpenoid synthase 3; ch...,sp|A4FVP2|TPS03_ARATH Terpenoid synthase 3; ch...,1,34,34,16.55,40.86,0.455,0.568,...,0.029,0.265,0.059,0.118,0.382,0.147,MPKRQAQRRFTRKTDSKTPSQPLVSRRSANYQPS,MPKRQAQRRFTRKTDSKTPSQPLVSRRSANYQPSLWQHEYLLSLGN...,565,N-terminal
3,3,sp|F4I316|SUN3_ARATH SUN domain-containing pro...,sp|F4I316|SUN3_ARATH SUN domain-containing pro...,1,292,292,54.52,122.24,0.427,0.552,...,0.164,0.123,0.058,0.027,0.384,0.240,MQRSCRTRRRVSVNKFNGRNSFYKVSLSLVFLLWVLLFFSTLLIS...,MQRSCRTRRRVSVNKFNGRNSFYKVSLSLVFLLWVLLFFSTLLISH...,660,N-terminal
4,4,sp|F4I316|SUN3_ARATH SUN domain-containing pro...,sp|F4I316|SUN3_ARATH SUN domain-containing pro...,415,496,82,28.27,67.04,0.438,0.561,...,0.220,0.171,0.012,0.085,0.317,0.195,DNKNAYKPREGDSEHKEKPMQQIESLEGDDGADKSTHREKEKEAP...,MQRSCRTRRRVSVNKFNGRNSFYKVSLSLVFLLWVLLFFSTLLISH...,660,middle

In [3]:

# Define the lower and upper bounds for filtering
min_length = 100
max_length = 150

# Filter the DataFrame
filtered_df = merged_df[(merged_df['Sequence Length'] >= min_length) & (merged_df['Sequence Length'] <= max_length)]

print(f"\nSub-DataFrame filtered for 'Sequence Length' between {min_length} and {max_length}:")
display(filtered_df)

Sub-DataFrame filtered for 'Sequence Length' between 100 and 150:

,Unnamed: 0,IDR ID,FASTA header,IDR start,IDR end,IDR len,Rg (A),Re (A),asphericity,scaling_exponent,...,fract_negative,fract_positive,fract_aro,fract_pro,fract_polar,fract_ali,sequence,Sequence_protein,Sequence Length,location
76,76,tr|Q9SN99|Q9SN99_ARATH Uncharacterized protein...,tr|Q9SN99|Q9SN99_ARATH Uncharacterized protein...,1,81,81,25.84,61.45,0.427,0.550,...,0.222,0.123,0.012,0.000,0.420,0.198,MEVKEICKSRKRHVALEINGGNKDRTDGGVEGGVDDDGAMVERSS...,MEVKEICKSRKRHVALEINGGNKDRTDGGVEGGVDDDGAMVERSSL...,117,N-terminal
78,78,tr|Q9SZH8|Q9SZH8_ARATH Uncharacterized protein...,tr|Q9SZH8|Q9SZH8_ARATH Uncharacterized protein...,1,50,50,21.33,51.98,0.448,0.583,...,0.140,0.260,0.040,0.040,0.360,0.160,MKYNLKHTEDKNFVKSKPLSKGSKQTIVGEKITKMKEESHKTKQT...,MKYNLKHTEDKNFVKSKPLSKGSKQTIVGEKITKMKEESHKTKQTK...,122,N-terminal
90,90,tr|F4HWT1|F4HWT1_ARATH Plant mobile domain pro...,tr|F4HWT1|F4HWT1_ARATH Plant mobile domain pro...,1,117,117,31.54,74.84,0.421,0.544,...,0.205,0.154,0.043,0.000,0.342,0.231,MKQRRKMLMEGSMHEKFASGCTNGDETRKAYKHKVLKSSDESNIH...,MKQRRKMLMEGSMHEKFASGCTNGDETRKAYKHKVLKSSDESNIHI...,117,IDP
114,114,sp|P92517|M760_ARATH Uncharacterized mitochond...,sp|P92517|M760_ARATH Uncharacterized mitochond...,1,109,109,30.07,70.68,0.408,0.525,...,0.092,0.156,0.101,0.046,0.321,0.275,MLRSGKELEEVVRDDKEEEQVVVRKAKQIVNFPLLGMLSSARYGL...,MLRSGKELEEVVRDDKEEEQVVVRKAKQIVNFPLLGMLSSARYGLR...,109,IDP
118,118,tr|Q67ZE4|Q67ZE4_ARATH TCP-1/cpn60 chaperonin ...,tr|Q67ZE4|Q67ZE4_ARATH TCP-1/cpn60 chaperonin ...,1,120,120,34.09,80.79,0.425,0.558,...,0.083,0.150,0.067,0.042,0.283,0.367,MALAFDEFGRPFIILREQDQKTRLKGIDAQKANISAGKAVARILR...,MALAFDEFGRPFIILREQDQKTRLKGIDAQKANISAGKAVARILRS...,120,IDP
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23574,23574,tr|A0A1P8B2A8|A0A1P8B2A8_ARATH Long chain acyl...,tr|A0A1P8B2A8|A0A1P8B2A8_ARATH Long chain acyl...,1,64,64,22.05,52.77,0.412,0.524,...,0.078,0.141,0.109,0.016,0.328,0.312,MKLQHIFISTILFNNLNIRLRIFTISEICNIYVQSSFKGKHKRER...,MKLQHIFISTILFNNLNIRLRIFTISEICNIYVQSSFKGKHKRERE...,130,N-terminal
23590,23590,sp|Q6NN00|AGP25_ARATH Classical arabinogalacta...,sp|Q6NN00|AGP25_ARATH Classical arabinogalacta...,1,116,116,36.40,85.94,0.442,0.570,...,0.069,0.009,0.078,0.181,0.328,0.336,MAFSFLNKLLIIFIFIFISLSSSSPTISLVQQLSPEIAPLLPSPG...,MAFSFLNKLLIIFIFIFISLSSSSPTISLVQQLSPEIAPLLPSPGD...,116,IDP
23594,23594,tr|Q8VY68|Q8VY68_ARATH Glycine-rich protein OS...,tr|Q8VY68|Q8VY68_ARATH Glycine-rich protein OS...,1,113,113,30.43,72.96,0.399,0.533,...,0.062,0.142,0.080,0.044,0.407,0.239,MAYVEGGVVKAKRPIWRLRTIKDFFLSIINLIQVFFVTMFSMEKS...,MAYVEGGVVKAKRPIWRLRTIKDFFLSIINLIQVFFVTMFSMEKSD...,113,IDP
23603,23603,tr|Q9C9I4|Q9C9I4_ARATH Uncharacterized protein...,tr|Q9C9I4|Q9C9I4_ARATH Uncharacterized protein...,1,56,56,23.73,56.92,0.468,0.594,...,0.286,0.018,0.000,0.089,0.411,0.196,MVPVTINSPPKPESSEEELSDSQVSNSSEDDDSMEDEPSDSENNN...,MVPVTINSPPKPESSEEELSDSQVSNSSEDDDSMEDEPSDSENNNG...,131,N-terminal
23614,23614,tr|Q9SZD3|Q9SZD3_ARATH Glycine-rich protein li...,tr|Q9SZD3|Q9SZD3_ARATH Glycine-rich protein li...,1,115,115,29.11,68.63,0.406,0.536,...,0.017,0.026,0.104,0.035,0.548,0.261,MAKWFFTIFLVFALASALACGARNVPVGLSDQKNYLGYGGGYSGV...,MAKWFFTIFLVFALASALACGARNVPVGLSDQKNYLGYGGGYSGVG...,115,IDP

In [4]:
import numpy as np
import matplotlib

import matplotlib.pyplot as plt
from matplotlib.pyplot import figure
	
# Set such that PDF fonts export in a manner that they
# are editable in illustrator/affinity
matplotlib.rcParams['pdf.fonttype'] = 42
matplotlib.rcParams['ps.fonttype'] = 42

# set to define axes linewidths
matplotlib.rcParams['axes.linewidth'] = 0.5

# this defines some prefactors so inline figures look nice
# on a retina macbook. These can be commented out without any
# issue and are solely asthetic.
%matplotlib inline
%config InlineBackend.figure_format='retina'

# UPDATE 2020-12-31 (my preferred font is Avenir...)
font = {'family' : 'avenir',
    	'weight' : 'normal'}

matplotlib.rc('font', **font)

from tqdm import tqdm
import pickle
from sparrow import Protein
import protfasta
from tqdm.auto import tqdm

In [19]:
#%pip uninstall sparrow
#%Y
#%pip uninstall -y sparrow
#%pip install git+https://git@github.com/idptools/sparrow.git
#%pip install shephard@git+git://github.com/holehouse-lab/shephard.git
#%pip install shephard
#%pip install torch scipy cython matplotlib
#%pip install mdtraj
#%pip install metapredict
#%pip install git+https://git@github.com/idptools/finches.git

3697.66s - pydevd: Sending message related to process being replaced timed-out after 5 seconds

Collecting git+https://****@github.com/idptools/finches.git
  Cloning https://****@github.com/idptools/finches.git to /tmp/pip-req-build-bln6vsj9
  Running command git clone --filter=blob:none --quiet 'https://****@github.com/idptools/finches.git' /tmp/pip-req-build-bln6vsj9
  Resolved https://****@github.com/idptools/finches.git to commit 5b52ba4023e9faf45e4e172e7681c05f86895b14
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: numpy in /home/wenyuantong/.local/share/pipx/venvs/jupyterlab/lib/python3.12/site-packages (from finches==0.1.3+2.g5b52ba4) (2.3.3)
Requirement already satisfied: afrc>=0.3.4 in /home/wenyuantong/.local/share/pipx/venvs/jupyterlab/lib/python3.12/site-packages (from finches==0.1.3+2.g5b52ba4) (0.3.7)
Requirement already satisfied: scipy in /home/wenyuantong/.local/share/pipx/venvs/jupyterlab/lib/python3.12/site-packages (from finches==0.1.3+2.g5b52ba4) (1.16.3)
Collecting soursop>=0.2.4 (from finches==0.1.3+2.g5b52ba4)
  Downloading soursop-0.2.6.tar.gz (8.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.6/8.6 MB 11.4 MB/s  0:00:00a 0:00:01m eta 0:00:01m
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: pandas in /home/wenyuantong/.local/share/pipx/venvs/jupyterlab/lib/python3.12/site-packages (from finches==0.1.3+2.g5b52ba4) (2.3.2)
Requirement already satisfied: metapredict in /home/wenyuantong/.local/share/pipx/venvs/jupyterlab/lib/python3.12/site-packages (from finches==0.1.3+2.g5b52ba4) (3.0.1)
Requirement already satisfied: ipython in /home/wenyuantong/.local/share/pipx/venvs/jupyterlab/lib/python3.12/site-packages (from finches==0.1.3+2.g5b52ba4) (9.5.0)
Requirement already satisfied: cython in /home/wenyuantong/.local/share/pipx/venvs/jupyterlab/lib/python3.12/site-packages (from soursop>=0.2.4->finches==0.1.3+2.g5b52ba4) (3.2.1)
Requirement already satisfied: mdtraj>=1.9.5 in /home/wenyuantong/.local/share/pipx/venvs/jupyterlab/lib/python3.12/site-packages (from soursop>=0.2.4->finches==0.1.3+2.g5b52ba4) (1.11.0)
Requirement already satisfied: threadpoolctl>=2.2.0 in /home/wenyuantong/.local/share/pipx/venvs/jupyterlab/lib/python3.12/site-packages (from soursop>=0.2.4->finches==0.1.3+2.g5b52ba4) (3.6.0)
Requirement already satisfied: natsort in /home/wenyuantong/.local/share/pipx/venvs/jupyterlab/lib/python3.12/site-packages (from soursop>=0.2.4->finches==0.1.3+2.g5b52ba4) (8.4.0)
Requirement already satisfied: matplotlib in /home/wenyuantong/.local/share/pipx/venvs/jupyterlab/lib/python3.12/site-packages (from soursop>=0.2.4->finches==0.1.3+2.g5b52ba4) (3.10.7)
Requirement already satisfied: pyparsing in /home/wenyuantong/.local/share/pipx/venvs/jupyterlab/lib/python3.12/site-packages (from mdtraj>=1.9.5->soursop>=0.2.4->finches==0.1.3+2.g5b52ba4) (3.2.5)
Requirement already satisfied: packaging in /home/wenyuantong/.local/share/pipx/venvs/jupyterlab/lib/python3.12/site-packages (from mdtraj>=1.9.5->soursop>=0.2.4->finches==0.1.3+2.g5b52ba4) (25.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/wenyuantong/.local/share/pipx/venvs/jupyterlab/lib/python3.12/site-packages (from pandas->finches==0.1.3+2.g5b52ba4) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /home/wenyuantong/.local/share/pipx/venvs/jupyterlab/lib/python3.12/site-packages (from pandas->finches==0.1.3+2.g5b52ba4) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /home/wenyuantong/.local/share/pipx/venvs/jupyterlab/lib/python3.12/site-packages (from pandas->finches==0.1.3+2.g5b52ba4) (2025.2)
Requirement already satisfied: six>=1.5 in /home/wenyuantong/.local/share/pipx/venvs/jupyterlab/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas->finches==0.1.3+2.g5b52ba4) (1.17.0)
Requirement already satisfied: decorator in /home/wenyuantong/.local/share/pipx/venvs/jupyterlab/lib/python3.12/site-packages (from ipython->finches==0.1.3+2.g5b52ba4) (5.2.1)
Requirement already satisfied: ipython-pygments-lexers in /home/wenyuantong/.local/share/pipx/venvs/jupyterlab/lib/python3.12/site-packages (from ipython->finches==0.1.3+2.g5b52ba4) (1.1.1)
Requirement already satisfied: jedi>=0.16 in /home/wenyuantong/.local/share/pipx/venvs/jupyterlab/lib/python3.12/site-packages (from ipython->finches==0.1.3+2.g5b52ba4) (0.19.2)
Requirement already satisfied: matplotlib-inline in /home/wenyuantong/.local/share/pipx/venvs/jupyterlab/lib/python3.12/site-packages (from ipython->finches==0.1.3+2.g5b52ba4) (0.1.7)
Requirement already satisfied: pexpect>4.3 in /home/wenyuantong/.local/share/pipx/venvs/jupyterlab/lib/python3.12/site-packages (from ipython->finches==0.1.3+2.g5b52ba4) (4.9.0)
Requirement already satisfied: prompt_toolkit<3.1.0,>=3.0.41 in /home/wenyuantong/.local/share/pipx/venvs/jupyterlab/lib/python3.12/site-packages (from ipython->finches==0.1.3+2.g5b52ba4) (3.0.52)
Requirement already satisfied: pygments>=2.4.0 in /home/wenyuantong/.local/share/pipx/venvs/jupyterlab/lib/python3.12/site-packages (from ipython->finches==0.1.3+2.g5b52ba4) (2.19.2)
Requirement already satisfied: stack_data in /home/wenyuantong/.local/share/pipx/venvs/jupyterlab/lib/python3.12/site-packages (from ipython->finches==0.1.3+2.g5b52ba4) (0.6.3)
Requirement already satisfied: traitlets>=5.13.0 in /home/wenyuantong/.local/share/pipx/venvs/jupyterlab/lib/python3.12/site-packages (from ipython->finches==0.1.3+2.g5b52ba4) (5.14.3)
Requirement already satisfied: wcwidth in /home/wenyuantong/.local/share/pipx/venvs/jupyterlab/lib/python3.12/site-packages (from prompt_toolkit<3.1.0,>=3.0.41->ipython->finches==0.1.3+2.g5b52ba4) (0.2.13)
Requirement already satisfied: parso<0.9.0,>=0.8.4 in /home/wenyuantong/.local/share/pipx/venvs/jupyterlab/lib/python3.12/site-packages (from jedi>=0.16->ipython->finches==0.1.3+2.g5b52ba4) (0.8.5)
Requirement already satisfied: ptyprocess>=0.5 in /home/wenyuantong/.local/share/pipx/venvs/jupyterlab/lib/python3.12/site-packages (from pexpect>4.3->ipython->finches==0.1.3+2.g5b52ba4) (0.7.0)
Requirement already satisfied: contourpy>=1.0.1 in /home/wenyuantong/.local/share/pipx/venvs/jupyterlab/lib/python3.12/site-packages (from matplotlib->soursop>=0.2.4->finches==0.1.3+2.g5b52ba4) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /home/wenyuantong/.local/share/pipx/venvs/jupyterlab/lib/python3.12/site-packages (from matplotlib->soursop>=0.2.4->finches==0.1.3+2.g5b52ba4) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /home/wenyuantong/.local/share/pipx/venvs/jupyterlab/lib/python3.12/site-packages (from matplotlib->soursop>=0.2.4->finches==0.1.3+2.g5b52ba4) (4.60.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /home/wenyuantong/.local/share/pipx/venvs/jupyterlab/lib/python3.12/site-packages (from matplotlib->soursop>=0.2.4->finches==0.1.3+2.g5b52ba4) (1.4.9)
Requirement already satisfied: pillow>=8 in /home/wenyuantong/.local/share/pipx/venvs/jupyterlab/lib/python3.12/site-packages (from matplotlib->soursop>=0.2.4->finches==0.1.3+2.g5b52ba4) (12.0.0)
Requirement already satisfied: torch in /home/wenyuantong/.local/share/pipx/venvs/jupyterlab/lib/python3.12/site-packages (from metapredict->finches==0.1.3+2.g5b52ba4) (2.9.1)
Requirement already satisfied: protfasta in /home/wenyuantong/.local/share/pipx/venvs/jupyterlab/lib/python3.12/site-packages (from metapredict->finches==0.1.3+2.g5b52ba4) (0.1.15.2)
Requirement already satisfied: urllib3 in /home/wenyuantong/.local/share/pipx/venvs/jupyterlab/lib/python3.12/site-packages (from metapredict->finches==0.1.3+2.g5b52ba4) (2.5.0)
Requirement already satisfied: tqdm in /home/wenyuantong/.local/share/pipx/venvs/jupyterlab/lib/python3.12/site-packages (from metapredict->finches==0.1.3+2.g5b52ba4) (4.67.1)
Requirement already satisfied: pytorch_lightning in /home/wenyuantong/.local/share/pipx/venvs/jupyterlab/lib/python3.12/site-packages (from metapredict->finches==0.1.3+2.g5b52ba4) (2.5.6)
Requirement already satisfied: getSequence>=2.2.1 in /home/wenyuantong/.local/share/pipx/venvs/jupyterlab/lib/python3.12/site-packages (from metapredict->finches==0.1.3+2.g5b52ba4) (2.2.1)
Requirement already satisfied: requests in /home/wenyuantong/.local/share/pipx/venvs/jupyterlab/lib/python3.12/site-packages (from getSequence>=2.2.1->metapredict->finches==0.1.3+2.g5b52ba4) (2.32.5)
Requirement already satisfied: PyYAML>5.4 in /home/wenyuantong/.local/share/pipx/venvs/jupyterlab/lib/python3.12/site-packages (from pytorch_lightning->metapredict->finches==0.1.3+2.g5b52ba4) (6.0.2)
Requirement already satisfied: fsspec>=2022.5.0 in /home/wenyuantong/.local/share/pipx/venvs/jupyterlab/lib/python3.12/site-packages (from fsspec[http]>=2022.5.0->pytorch_lightning->metapredict->finches==0.1.3+2.g5b52ba4) (2025.10.0)
Requirement already satisfied: torchmetrics>0.7.0 in /home/wenyuantong/.local/share/pipx/venvs/jupyterlab/lib/python3.12/site-packages (from pytorch_lightning->metapredict->finches==0.1.3+2.g5b52ba4) (1.8.2)
Requirement already satisfied: typing-extensions>4.5.0 in /home/wenyuantong/.local/share/pipx/venvs/jupyterlab/lib/python3.12/site-packages (from pytorch_lightning->metapredict->finches==0.1.3+2.g5b52ba4) (4.15.0)
Requirement already satisfied: lightning-utilities>=0.10.0 in /home/wenyuantong/.local/share/pipx/venvs/jupyterlab/lib/python3.12/site-packages (from pytorch_lightning->metapredict->finches==0.1.3+2.g5b52ba4) (0.15.2)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /home/wenyuantong/.local/share/pipx/venvs/jupyterlab/lib/python3.12/site-packages (from fsspec[http]>=2022.5.0->pytorch_lightning->metapredict->finches==0.1.3+2.g5b52ba4) (3.13.2)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /home/wenyuantong/.local/share/pipx/venvs/jupyterlab/lib/python3.12/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2022.5.0->pytorch_lightning->metapredict->finches==0.1.3+2.g5b52ba4) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /home/wenyuantong/.local/share/pipx/venvs/jupyterlab/lib/python3.12/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2022.5.0->pytorch_lightning->metapredict->finches==0.1.3+2.g5b52ba4) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /home/wenyuantong/.local/share/pipx/venvs/jupyterlab/lib/python3.12/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2022.5.0->pytorch_lightning->metapredict->finches==0.1.3+2.g5b52ba4) (25.3.0)
Requirement already satisfied: frozenlist>=1.1.1 in /home/wenyuantong/.local/share/pipx/venvs/jupyterlab/lib/python3.12/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2022.5.0->pytorch_lightning->metapredict->finches==0.1.3+2.g5b52ba4) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /home/wenyuantong/.local/share/pipx/venvs/jupyterlab/lib/python3.12/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2022.5.0->pytorch_lightning->metapredict->finches==0.1.3+2.g5b52ba4) (6.7.0)
Requirement already satisfied: propcache>=0.2.0 in /home/wenyuantong/.local/share/pipx/venvs/jupyterlab/lib/python3.12/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2022.5.0->pytorch_lightning->metapredict->finches==0.1.3+2.g5b52ba4) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /home/wenyuantong/.local/share/pipx/venvs/jupyterlab/lib/python3.12/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2022.5.0->pytorch_lightning->metapredict->finches==0.1.3+2.g5b52ba4) (1.22.0)
Requirement already satisfied: idna>=2.0 in /home/wenyuantong/.local/share/pipx/venvs/jupyterlab/lib/python3.12/site-packages (from yarl<2.0,>=1.17.0->aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2022.5.0->pytorch_lightning->metapredict->finches==0.1.3+2.g5b52ba4) (3.10)
Requirement already satisfied: setuptools in /home/wenyuantong/.local/share/pipx/venvs/jupyterlab/lib/python3.12/site-packages (from lightning-utilities>=0.10.0->pytorch_lightning->metapredict->finches==0.1.3+2.g5b52ba4) (80.9.0)
Requirement already satisfied: filelock in /home/wenyuantong/.local/share/pipx/venvs/jupyterlab/lib/python3.12/site-packages (from torch->metapredict->finches==0.1.3+2.g5b52ba4) (3.20.0)
Requirement already satisfied: sympy>=1.13.3 in /home/wenyuantong/.local/share/pipx/venvs/jupyterlab/lib/python3.12/site-packages (from torch->metapredict->finches==0.1.3+2.g5b52ba4) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /home/wenyuantong/.local/share/pipx/venvs/jupyterlab/lib/python3.12/site-packages (from torch->metapredict->finches==0.1.3+2.g5b52ba4) (3.5)
Requirement already satisfied: jinja2 in /home/wenyuantong/.local/share/pipx/venvs/jupyterlab/lib/python3.12/site-packages (from torch->metapredict->finches==0.1.3+2.g5b52ba4) (3.1.6)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93 in /home/wenyuantong/.local/share/pipx/venvs/jupyterlab/lib/python3.12/site-packages (from torch->metapredict->finches==0.1.3+2.g5b52ba4) (12.8.93)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90 in /home/wenyuantong/.local/share/pipx/venvs/jupyterlab/lib/python3.12/site-packages (from torch->metapredict->finches==0.1.3+2.g5b52ba4) (12.8.90)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90 in /home/wenyuantong/.local/share/pipx/venvs/jupyterlab/lib/python3.12/site-packages (from torch->metapredict->finches==0.1.3+2.g5b52ba4) (12.8.90)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /home/wenyuantong/.local/share/pipx/venvs/jupyterlab/lib/python3.12/site-packages (from torch->metapredict->finches==0.1.3+2.g5b52ba4) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1 in /home/wenyuantong/.local/share/pipx/venvs/jupyterlab/lib/python3.12/site-packages (from torch->metapredict->finches==0.1.3+2.g5b52ba4) (12.8.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83 in /home/wenyuantong/.local/share/pipx/venvs/jupyterlab/lib/python3.12/site-packages (from torch->metapredict->finches==0.1.3+2.g5b52ba4) (11.3.3.83)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90 in /home/wenyuantong/.local/share/pipx/venvs/jupyterlab/lib/python3.12/site-packages (from torch->metapredict->finches==0.1.3+2.g5b52ba4) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90 in /home/wenyuantong/.local/share/pipx/venvs/jupyterlab/lib/python3.12/site-packages (from torch->metapredict->finches==0.1.3+2.g5b52ba4) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93 in /home/wenyuantong/.local/share/pipx/venvs/jupyterlab/lib/python3.12/site-packages (from torch->metapredict->finches==0.1.3+2.g5b52ba4) (12.5.8.93)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /home/wenyuantong/.local/share/pipx/venvs/jupyterlab/lib/python3.12/site-packages (from torch->metapredict->finches==0.1.3+2.g5b52ba4) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /home/wenyuantong/.local/share/pipx/venvs/jupyterlab/lib/python3.12/site-packages (from torch->metapredict->finches==0.1.3+2.g5b52ba4) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.3.20 in /home/wenyuantong/.local/share/pipx/venvs/jupyterlab/lib/python3.12/site-packages (from torch->metapredict->finches==0.1.3+2.g5b52ba4) (3.3.20)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90 in /home/wenyuantong/.local/share/pipx/venvs/jupyterlab/lib/python3.12/site-packages (from torch->metapredict->finches==0.1.3+2.g5b52ba4) (12.8.90)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93 in /home/wenyuantong/.local/share/pipx/venvs/jupyterlab/lib/python3.12/site-packages (from torch->metapredict->finches==0.1.3+2.g5b52ba4) (12.8.93)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3 in /home/wenyuantong/.local/share/pipx/venvs/jupyterlab/lib/python3.12/site-packages (from torch->metapredict->finches==0.1.3+2.g5b52ba4) (1.13.1.3)
Requirement already satisfied: triton==3.5.1 in /home/wenyuantong/.local/share/pipx/venvs/jupyterlab/lib/python3.12/site-packages (from torch->metapredict->finches==0.1.3+2.g5b52ba4) (3.5.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /home/wenyuantong/.local/share/pipx/venvs/jupyterlab/lib/python3.12/site-packages (from sympy>=1.13.3->torch->metapredict->finches==0.1.3+2.g5b52ba4) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /home/wenyuantong/.local/share/pipx/venvs/jupyterlab/lib/python3.12/site-packages (from jinja2->torch->metapredict->finches==0.1.3+2.g5b52ba4) (3.0.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /home/wenyuantong/.local/share/pipx/venvs/jupyterlab/lib/python3.12/site-packages (from requests->getSequence>=2.2.1->metapredict->finches==0.1.3+2.g5b52ba4) (3.4.3)
Requirement already satisfied: certifi>=2017.4.17 in /home/wenyuantong/.local/share/pipx/venvs/jupyterlab/lib/python3.12/site-packages (from requests->getSequence>=2.2.1->metapredict->finches==0.1.3+2.g5b52ba4) (2025.8.3)
Requirement already satisfied: executing>=1.2.0 in /home/wenyuantong/.local/share/pipx/venvs/jupyterlab/lib/python3.12/site-packages (from stack_data->ipython->finches==0.1.3+2.g5b52ba4) (2.2.1)
Requirement already satisfied: asttokens>=2.1.0 in /home/wenyuantong/.local/share/pipx/venvs/jupyterlab/lib/python3.12/site-packages (from stack_data->ipython->finches==0.1.3+2.g5b52ba4) (3.0.0)
Requirement already satisfied: pure-eval in /home/wenyuantong/.local/share/pipx/venvs/jupyterlab/lib/python3.12/site-packages (from stack_data->ipython->finches==0.1.3+2.g5b52ba4) (0.2.3)
Building wheels for collected packages: finches, soursop
  Building wheel for finches (pyproject.toml) ... done
  Created wheel for finches: filename=finches-0.1.3+2.g5b52ba4-cp312-cp312-linux_x86_64.whl size=2188607 sha256=577fc10f92525b4dee232957ae747c61a024bb79c1b711d50c84a07211f4b329
  Stored in directory: /tmp/pip-ephem-wheel-cache-ake34lq2/wheels/5b/f6/52/65ff13a202bd44ffa448fab752a38a81580c6dfac38df772da
  Building wheel for soursop (pyproject.toml) ... done
  Created wheel for soursop: filename=soursop-0.2.6-py3-none-any.whl size=8594518 sha256=c392cde2356d68b471b0447005666288a4351bc616f65bd395398bba4d376dd1
  Stored in directory: /home/wenyuantong/.cache/pip/wheels/8a/b1/d2/c708382f213415cb923af966aa74901779fee5da908531e97a
Successfully built finches soursop
Installing collected packages: soursop, finches
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/2 [finches]━━━ 1/2 [finches]
Successfully installed finches-0.1.3+2.g5b52ba4 soursop-0.2.6

[notice] A new release of pip is available: 25.2 -> 25.3
[notice] To update, run: /home/wenyuantong/.local/share/pipx/venvs/jupyterlab/bin/python -m pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [5]:
from shephard.apis import uniprot
from shephard.interfaces import si_domains, si_protein_attributes

from finches import Mpipi_frontend, CALVADOS_frontend
mf = Mpipi_frontend()
cf = CALVADOS_frontend()

/home/wenyuantong/.local/share/pipx/venvs/jupyterlab/lib/python3.12/site-packages/finches/forcefields/calvados.py:236: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0.038286503882254706' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  r.loc['H','q'] = 1. / ( 1 + 10**(self.pH-6) )