In [17]:
from Bio import SeqIO
import pandas as pd
import numpy as np

In [8]:
# Replace 'your_file.csv' with the actual path to your CSV file
try:
    df_IDR = pd.read_csv('~/Desktop/data/filtered_IDR_psytec.csv')
    # Assuming the column with lengths is the first column (index 0)
    # You might need to change '0' to the actual column name or index if different
except FileNotFoundError:
    print("Error: 'your_file.csv' not found. Please replace with the correct file path.")
except Exception as e:
    print(f"An error occurred: {e}")

In [28]:
display(df_IDR)

,IDR ID,FASTA header,IDR start,IDR end,IDR len,Rg (A),Re (A),asphericity,scaling_exponent,prefactor,FCR,NCPR,kappa,fract_negative,fract_positive,fract_aro,fract_pro,fract_polar,fract_ali,sequence
0,HopX1a <unknown description>_1_88,HopX1a <unknown description>,1,88,88,28.94,70.23,0.439,0.554,6.717,0.148,0.034,0.224,0.057,0.091,0.034,0.125,0.432,0.250,MRIHSAGHSLPAPGPSVETTEKAVQSSSAQNPASCSSQTERPEAG...
1,HopX1a <unknown description>_200_247,HopX1a <unknown description>,200,247,48,19.47,47.56,0.427,0.548,6.297,0.250,-0.083,0.148,0.167,0.083,0.042,0.083,0.333,0.292,SPREKIHLAEQPGKDHVWAETDNSSAGSSPIVMDPWSNGAAILAEDSR
2,HopX1a <unknown description>_298_380,HopX1a <unknown description>,298,380,83,27.59,66.03,0.435,0.550,6.139,0.301,0.060,0.198,0.120,0.181,0.024,0.072,0.253,0.349,NVSPLEGGRYQPEKSVLDEAFARRVSDKLNSDDPRRALQMEIEAV...
3,HopX1c <unknown description>_1_87,HopX1c <unknown description>,1,87,87,28.95,70.08,0.427,0.550,6.856,0.126,0.034,0.180,0.046,0.080,0.034,0.161,0.437,0.241,MKIHNSGLTPPLPGISNGNVGKAAQSSMTQPQSQQGSHSLPPESS...
4,HopX1c <unknown description>_212_267,HopX1c <unknown description>,212,267,56,20.48,48.39,0.425,0.535,6.814,0.268,-0.125,0.305,0.196,0.071,0.089,0.018,0.393,0.232,ASTEEDHVWAETDESQSGTSTIVMDPWSNGSAIFAEDSRFAKNRN...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
588,HopZ5a <unknown description>_1_44,HopZ5a <unknown description>,1,44,44,18.59,44.59,0.418,0.548,6.319,0.182,-0.045,0.486,0.114,0.068,0.091,0.091,0.500,0.114,MGLCASKPRTTSGYNTYASYNSGSSTPEPEETGSSRVTETHPEF
589,HopZ5a <unknown description>_252_346,HopZ5a <unknown description>,252,346,95,28.39,67.53,0.420,0.535,6.398,0.326,0.011,0.200,0.158,0.168,0.042,0.032,0.337,0.263,PREHKSETVSGIEVIDGTKILPAVFFKHTHSRSTINDAIEEQPEL...
590,HopZ5b <unknown description>_1_44,HopZ5b <unknown description>,1,44,44,18.41,44.70,0.425,0.546,6.189,0.205,-0.023,0.274,0.114,0.091,0.091,0.091,0.455,0.136,MGLCVSKPRTTSDYNTYASYNSGPSTPKHEETGSSRMTEAHPEF
591,HopZ5b <unknown description>_283_346,HopZ5b <unknown description>,283,346,64,22.49,53.66,0.420,0.524,6.446,0.359,0.016,0.237,0.172,0.188,0.031,0.016,0.328,0.266,RSTINDAIEEQPELADRNVSTNRESAHQTLSERVADFRVQRSERS...
592,AvrB1b <unknown description>_1_31,AvrB1b <unknown description>,1,31,31,15.10,37.46,0.448,0.575,6.191,0.129,0.065,0.387,0.032,0.097,0.065,0.065,0.484,0.226,MGCVSSKSTTVLSPQTSFNEASRTSFRALPG

In [29]:
# Find the maximum value in 'col1'
max_value_col1 = df_IDR[' IDR len'].max()

print(f"\nMaximum value in 'col1': {max_value_col1}")

Maximum value in 'col1': 408

In [30]:
# Find the median value in 'col1'
median_value_col1 = df_IDR[' IDR len'].median()

print(f"Median value in 'col1': {median_value_col1}")

Median value in 'col1': 69.0

In [10]:
# Assuming your FASTA file is named 'example.fasta' and is in the content directory
fasta_file = "/home/wenyuantong/Desktop/data/PsyTEC_2.fasta"

# Create lists to store data
names = []
sequences = []
lengths = []

# Parse the FASTA file
for record in SeqIO.parse(fasta_file, "fasta"):
    names.append(record.description)
    sequences.append(str(record.seq))
    lengths.append(len(record.seq))

# Create a pandas DataFrame
data = {'Name': names, 'Sequence_protein': sequences, 'Sequence Length': lengths}
df = pd.DataFrame(data)

# Display the DataFrame
display(df.head())

,Name,Sequence_protein,Sequence Length
0,HopX1a <unknown description>,MRIHSAGHSLPAPGPSVETTEKAVQSSSAQNPASCSSQTERPEAGS...,381
1,HopX1c <unknown description>,MKIHNSGLTPPLPGISNGNVGKAAQSSMTQPQSQQGSHSLPPESSE...,385
2,HopX1b <unknown description>,MKIHNAGVTGPLPSISNEGAGKAAQSSSTQPQSQPESHGPTPESSE...,385
3,HopX1i <unknown description>,MKIHNAGPSIPMPAPSIESAGKTAQSSLAQPQSQRATPVSPSETSD...,385
4,HopX1e <unknown description>,MRIHSSGHGICAPVSSAETVEKAVQSSAQAQNEASHSGPSEHPESR...,383

In [11]:
df_IDR[' FASTA header'] = df_IDR[' FASTA header'].str.lstrip()

In [12]:
df['Name'] = df['Name'].str.replace(',', ';')

print("\nDataFrame after replacing ',' with ';':")
display(df.head())

DataFrame after replacing ',' with ';':

,Name,Sequence_protein,Sequence Length
0,HopX1a <unknown description>,MRIHSAGHSLPAPGPSVETTEKAVQSSSAQNPASCSSQTERPEAGS...,381
1,HopX1c <unknown description>,MKIHNSGLTPPLPGISNGNVGKAAQSSMTQPQSQQGSHSLPPESSE...,385
2,HopX1b <unknown description>,MKIHNAGVTGPLPSISNEGAGKAAQSSSTQPQSQPESHGPTPESSE...,385
3,HopX1i <unknown description>,MKIHNAGPSIPMPAPSIESAGKTAQSSLAQPQSQRATPVSPSETSD...,385
4,HopX1e <unknown description>,MRIHSSGHGICAPVSSAETVEKAVQSSAQAQNEASHSGPSEHPESR...,383

In [13]:
merged_df = pd.merge(df_IDR, df, left_on=' FASTA header', right_on='Name', how='left')

merged_df = merged_df.drop('Name', axis=1)

# Display the updated DataFrame
display(merged_df.head())

,IDR ID,FASTA header,IDR start,IDR end,IDR len,Rg (A),Re (A),asphericity,scaling_exponent,prefactor,...,kappa,fract_negative,fract_positive,fract_aro,fract_pro,fract_polar,fract_ali,sequence,Sequence_protein,Sequence Length
0,HopX1a <unknown description>_1_88,HopX1a <unknown description>,1,88,88,28.94,70.23,0.439,0.554,6.717,...,0.224,0.057,0.091,0.034,0.125,0.432,0.250,MRIHSAGHSLPAPGPSVETTEKAVQSSSAQNPASCSSQTERPEAG...,MRIHSAGHSLPAPGPSVETTEKAVQSSSAQNPASCSSQTERPEAGS...,381
1,HopX1a <unknown description>_200_247,HopX1a <unknown description>,200,247,48,19.47,47.56,0.427,0.548,6.297,...,0.148,0.167,0.083,0.042,0.083,0.333,0.292,SPREKIHLAEQPGKDHVWAETDNSSAGSSPIVMDPWSNGAAILAEDSR,MRIHSAGHSLPAPGPSVETTEKAVQSSSAQNPASCSSQTERPEAGS...,381
2,HopX1a <unknown description>_298_380,HopX1a <unknown description>,298,380,83,27.59,66.03,0.435,0.550,6.139,...,0.198,0.120,0.181,0.024,0.072,0.253,0.349,NVSPLEGGRYQPEKSVLDEAFARRVSDKLNSDDPRRALQMEIEAV...,MRIHSAGHSLPAPGPSVETTEKAVQSSSAQNPASCSSQTERPEAGS...,381
3,HopX1c <unknown description>_1_87,HopX1c <unknown description>,1,87,87,28.95,70.08,0.427,0.550,6.856,...,0.180,0.046,0.080,0.034,0.161,0.437,0.241,MKIHNSGLTPPLPGISNGNVGKAAQSSMTQPQSQQGSHSLPPESS...,MKIHNSGLTPPLPGISNGNVGKAAQSSMTQPQSQQGSHSLPPESSE...,385
4,HopX1c <unknown description>_212_267,HopX1c <unknown description>,212,267,56,20.48,48.39,0.425,0.535,6.814,...,0.305,0.196,0.071,0.089,0.018,0.393,0.232,ASTEEDHVWAETDESQSGTSTIVMDPWSNGSAIFAEDSRFAKNRN...,MKIHNSGLTPPLPGISNGNVGKAAQSSMTQPQSQQGSHSLPPESSE...,385

In [20]:
display(merged_df)

,IDR ID,FASTA header,IDR start,IDR end,IDR len,Rg (A),Re (A),asphericity,scaling_exponent,prefactor,...,fract_negative,fract_positive,fract_aro,fract_pro,fract_polar,fract_ali,sequence,Sequence_protein,Sequence Length,location
0,HopX1a <unknown description>_1_88,HopX1a <unknown description>,1,88,88,28.94,70.23,0.439,0.554,6.717,...,0.057,0.091,0.034,0.125,0.432,0.250,MRIHSAGHSLPAPGPSVETTEKAVQSSSAQNPASCSSQTERPEAG...,MRIHSAGHSLPAPGPSVETTEKAVQSSSAQNPASCSSQTERPEAGS...,381,N-terminal
1,HopX1a <unknown description>_200_247,HopX1a <unknown description>,200,247,48,19.47,47.56,0.427,0.548,6.297,...,0.167,0.083,0.042,0.083,0.333,0.292,SPREKIHLAEQPGKDHVWAETDNSSAGSSPIVMDPWSNGAAILAEDSR,MRIHSAGHSLPAPGPSVETTEKAVQSSSAQNPASCSSQTERPEAGS...,381,Middle
2,HopX1a <unknown description>_298_380,HopX1a <unknown description>,298,380,83,27.59,66.03,0.435,0.550,6.139,...,0.120,0.181,0.024,0.072,0.253,0.349,NVSPLEGGRYQPEKSVLDEAFARRVSDKLNSDDPRRALQMEIEAV...,MRIHSAGHSLPAPGPSVETTEKAVQSSSAQNPASCSSQTERPEAGS...,381,C-terminal
3,HopX1c <unknown description>_1_87,HopX1c <unknown description>,1,87,87,28.95,70.08,0.427,0.550,6.856,...,0.046,0.080,0.034,0.161,0.437,0.241,MKIHNSGLTPPLPGISNGNVGKAAQSSMTQPQSQQGSHSLPPESS...,MKIHNSGLTPPLPGISNGNVGKAAQSSMTQPQSQQGSHSLPPESSE...,385,N-terminal
4,HopX1c <unknown description>_212_267,HopX1c <unknown description>,212,267,56,20.48,48.39,0.425,0.535,6.814,...,0.196,0.071,0.089,0.018,0.393,0.232,ASTEEDHVWAETDESQSGTSTIVMDPWSNGSAIFAEDSRFAKNRN...,MKIHNSGLTPPLPGISNGNVGKAAQSSMTQPQSQQGSHSLPPESSE...,385,Middle
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
588,HopZ5a <unknown description>_1_44,HopZ5a <unknown description>,1,44,44,18.59,44.59,0.418,0.548,6.319,...,0.114,0.068,0.091,0.091,0.500,0.114,MGLCASKPRTTSGYNTYASYNSGSSTPEPEETGSSRVTETHPEF,MGLCASKPRTTSGYNTYASYNSGSSTPEPEETGSSRVTETHPEFRS...,346,N-terminal
589,HopZ5a <unknown description>_252_346,HopZ5a <unknown description>,252,346,95,28.39,67.53,0.420,0.535,6.398,...,0.158,0.168,0.042,0.032,0.337,0.263,PREHKSETVSGIEVIDGTKILPAVFFKHTHSRSTINDAIEEQPEL...,MGLCASKPRTTSGYNTYASYNSGSSTPEPEETGSSRVTETHPEFRS...,346,C-terminal
590,HopZ5b <unknown description>_1_44,HopZ5b <unknown description>,1,44,44,18.41,44.70,0.425,0.546,6.189,...,0.114,0.091,0.091,0.091,0.455,0.136,MGLCVSKPRTTSDYNTYASYNSGPSTPKHEETGSSRMTEAHPEF,MGLCVSKPRTTSDYNTYASYNSGPSTPKHEETGSSRMTEAHPEFRS...,346,N-terminal
591,HopZ5b <unknown description>_283_346,HopZ5b <unknown description>,283,346,64,22.49,53.66,0.420,0.524,6.446,...,0.172,0.188,0.031,0.016,0.328,0.266,RSTINDAIEEQPELADRNVSTNRESAHQTLSERVADFRVQRSERS...,MGLCVSKPRTTSDYNTYASYNSGPSTPKHEETGSSRMTEAHPEFRS...,346,C-terminal
592,AvrB1b <unknown description>_1_31,AvrB1b <unknown description>,1,31,31,15.10,37.46,0.448,0.575,6.191,...,0.032,0.097,0.065,0.065,0.484,0.226,MGCVSSKSTTVLSPQTSFNEASRTSFRALPG,MGCVSSKSTTVLSPQTSFNEASRTSFRALPGPSQRQLEVYDQCLIG...,321,N-terminal

In [14]:
df_with_nan = merged_df[merged_df["Sequence_protein"].isna()]

print(f"\nRows where the Sequence_protein column has NaN values:")
display(df_with_nan)

Rows where the Sequence_protein column has NaN values:

Empty DataFrame
Columns: [IDR ID,  FASTA header,  IDR start,  IDR end,  IDR len,  Rg (A),  Re (A),  asphericity,  scaling_exponent,  prefactor,  FCR,  NCPR,  kappa,  fract_negative,  fract_positive,  fract_aro,  fract_pro,  fract_polar,  fract_ali,  sequence, Sequence_protein, Sequence Length]
Index: []

[0 rows x 22 columns]

In [15]:
merged_df.to_csv('/home/wenyuantong/Desktop/data/psytec_IDR_merged_df.csv', index=True)

In [18]:
# Define the conditions
conditions = [
    # First condition: 'IDR start' between 1 and 20 (inclusive) and 'IDR end' less than 'sequence length'
    (merged_df[' IDR start'] >= 1) & (merged_df[' IDR start'] <= 20) & (merged_df[' IDR end'] < merged_df['Sequence Length']),
    # Second condition: 'IDR start' is 1 and 'IDR end' is equal to 'sequence length'
    (merged_df[' IDR start'] == 1) & (merged_df[' IDR end'] == merged_df['Sequence Length']),
    # Third condition: 'IDR start' is greater than 1 and 'IDR end' is between 'sequence length' and 20 before (inclusive)
    (merged_df[' IDR start'] > 1) & (merged_df[' IDR end'] <= merged_df['Sequence Length']) & (merged_df[' IDR end'] >= merged_df['Sequence Length'] - 20),
    # Fourth condition: 'IDR start' is greater than 1 and 'IDR end' is less than 'sequence length' (and not covered by the third condition)
    #(merged_df[' IDR start'] > 1) & (merged_df[' IDR end'] < merged_df['Sequence Length']) & (merged_df[' IDR end'] < merged_df['Sequence Length'] - 20)
    (merged_df[' IDR start'] > 1) & (merged_df[' IDR end'] < merged_df['Sequence Length']) &
    ~((merged_df[' IDR start'] >= 1) & (merged_df[' IDR start'] <= 20)) & # Exclude first condition's start range
    ~((merged_df[' IDR end'] <= merged_df['Sequence Length']) & (merged_df[' IDR end'] >= merged_df['Sequence Length'] - 20)) # Exclude third condition's end range
]

# Define the corresponding values for the new 'location' column
values = ['N-terminal', 'IDP', 'C-terminal', 'Middle']

# Create the new 'location' column using np.select
merged_df['location'] = np.select(conditions, values, default='unknown') # 'unknown' for cases that don't match any condition

print("\nDataFrame with 'location' column:")
display(merged_df.head())

DataFrame with 'location' column:

,IDR ID,FASTA header,IDR start,IDR end,IDR len,Rg (A),Re (A),asphericity,scaling_exponent,prefactor,...,fract_negative,fract_positive,fract_aro,fract_pro,fract_polar,fract_ali,sequence,Sequence_protein,Sequence Length,location
0,HopX1a <unknown description>_1_88,HopX1a <unknown description>,1,88,88,28.94,70.23,0.439,0.554,6.717,...,0.057,0.091,0.034,0.125,0.432,0.250,MRIHSAGHSLPAPGPSVETTEKAVQSSSAQNPASCSSQTERPEAG...,MRIHSAGHSLPAPGPSVETTEKAVQSSSAQNPASCSSQTERPEAGS...,381,N-terminal
1,HopX1a <unknown description>_200_247,HopX1a <unknown description>,200,247,48,19.47,47.56,0.427,0.548,6.297,...,0.167,0.083,0.042,0.083,0.333,0.292,SPREKIHLAEQPGKDHVWAETDNSSAGSSPIVMDPWSNGAAILAEDSR,MRIHSAGHSLPAPGPSVETTEKAVQSSSAQNPASCSSQTERPEAGS...,381,Middle
2,HopX1a <unknown description>_298_380,HopX1a <unknown description>,298,380,83,27.59,66.03,0.435,0.550,6.139,...,0.120,0.181,0.024,0.072,0.253,0.349,NVSPLEGGRYQPEKSVLDEAFARRVSDKLNSDDPRRALQMEIEAV...,MRIHSAGHSLPAPGPSVETTEKAVQSSSAQNPASCSSQTERPEAGS...,381,C-terminal
3,HopX1c <unknown description>_1_87,HopX1c <unknown description>,1,87,87,28.95,70.08,0.427,0.550,6.856,...,0.046,0.080,0.034,0.161,0.437,0.241,MKIHNSGLTPPLPGISNGNVGKAAQSSMTQPQSQQGSHSLPPESS...,MKIHNSGLTPPLPGISNGNVGKAAQSSMTQPQSQQGSHSLPPESSE...,385,N-terminal
4,HopX1c <unknown description>_212_267,HopX1c <unknown description>,212,267,56,20.48,48.39,0.425,0.535,6.814,...,0.196,0.071,0.089,0.018,0.393,0.232,ASTEEDHVWAETDESQSGTSTIVMDPWSNGSAIFAEDSRFAKNRN...,MKIHNSGLTPPLPGISNGNVGKAAQSSMTQPQSQQGSHSLPPESSE...,385,Middle

In [26]:
# Filter the DataFrame for rows where 'location' is 'unknown'
unknown_location_df = merged_df[merged_df['location'] == 'IDP']

print("\nDataFrame with only 'unknown' locations:")
display(unknown_location_df)

DataFrame with only 'unknown' locations:

,IDR ID,FASTA header,IDR start,IDR end,IDR len,Rg (A),Re (A),asphericity,scaling_exponent,prefactor,...,fract_negative,fract_positive,fract_aro,fract_pro,fract_polar,fract_ali,sequence,Sequence_protein,Sequence Length,location
421,AvrE1q <unknown description>_1_258,AvrE1q <unknown description>,1,258,258,53.50,126.41,0.415,0.558,6.309,...,0.093,0.124,0.019,0.070,0.426,0.267,MHSSSIHRNTGSIIQPPVPANTNAATDLQQKIEQPKQRSSHSLSS...,MHSSSIHRNTGSIIQPPVPANTNAATDLQQKIEQPKQRSSHSLSSV...,258,IDP
432,AvrPto1g <unknown description>_1_160,AvrPto1g <unknown description>,1,160,160,34.70,82.36,0.379,0.491,6.819,...,0.087,0.087,0.056,0.056,0.425,0.281,MGNNCVGGATSARQVYSPDRVSNSSDDPNHLTASQLLNVRQQLAE...,MGNNCVGGATSARQVYSPDRVSNSSDDPNHLTASQLLNVRQQLAES...,160,IDP
433,AvrPto1j <unknown description>_1_267,AvrPto1j <unknown description>,1,267,267,48.14,116.31,0.388,0.525,6.767,...,0.082,0.090,0.052,0.064,0.434,0.266,MGGLVQSPPPVGANRSHSTGRGRSNLLSATHRVCPGGMTQTKGSP...,MGGLVQSPPPVGANRSHSTGRGRSNLLSATHRVCPGGMTQTKGSPI...,267,IDP
437,AvrRpm1g <unknown description>_1_229,AvrRpm1g <unknown description>,1,229,229,43.46,99.61,0.397,0.520,6.590,...,0.122,0.118,0.079,0.031,0.419,0.231,MGYNVSNTSRNTGYYSGYESHQEPRGASSSSGNQHRGYEADSEQS...,MGYNVSNTSRNTGYYSGYESHQEPRGASSSSGNQHRGYEADSEQSG...,229,IDP
476,HopAG1e <unknown description>_1_57,HopAG1e <unknown description>,1,57,57,20.74,49.01,0.415,0.525,6.446,...,0.053,0.088,0.088,0.070,0.456,0.246,MNPITHSFNHLGFSNAQSTSALAPGGNKVPNFVSRGRGQGIPLEH...,MNPITHSFNHLGFSNAQSTSALAPGGNKVPNFVSRGRGQGIPLEHF...,57,IDP
479,HopAG1n <unknown description>_1_111,HopAG1n <unknown description>,1,111,111,30.20,70.71,0.406,0.529,6.522,...,0.108,0.126,0.081,0.063,0.369,0.243,MINPVKHNFSHLGFSNAQSTSALGPASNKVPNFVSRGRGKGVPVE...,MINPVKHNFSHLGFSNAQSTSALGPASNKVPNFVSRGRGKGVPVEQ...,111,IDP
481,HopAH1aa <unknown description>_1_86,HopAH1aa <unknown description>,1,86,86,27.31,65.95,0.422,0.547,6.430,...,0.058,0.058,0.047,0.093,0.558,0.186,MSMNTSVSNNSPGWSPVSSGNQAPSPDYSGKSSSNAVHFLPPEST...,MSMNTSVSNNSPGWSPVSSGNQAPSPDYSGKSSSNAVHFLPPESTQ...,86,IDP
484,HopAI1f <unknown description>_1_69,HopAI1f <unknown description>,1,69,69,24.92,61.44,0.422,0.566,6.387,...,0.072,0.130,0.029,0.087,0.348,0.333,MPLSKPMLSLKLNTQLTSPPVKKDTGAELSRLNKGEVLANTQTRF...,MPLSKPMLSLKLNTQLTSPPVKKDTGAELSRLNKGEVLANTQTRFA...,69,IDP
485,HopAI1h <unknown description>_1_75,HopAI1h <unknown description>,1,75,75,25.78,63.85,0.423,0.564,6.151,...,0.040,0.173,0.040,0.080,0.293,0.373,MPINRPAFNLKLNTAIAQPTVKKDAGAELRRLNQSEVRANTQTRF...,MPINRPAFNLKLNTAIAQPTVKKDAGAELRRLNQSEVRANTQTRFA...,75,IDP
487,HopAI1l <unknown description>_1_54,HopAI1l <unknown description>,1,54,54,20.94,51.66,0.429,0.551,6.413,...,0.056,0.167,0.037,0.074,0.333,0.333,MPINRPAFNLKLNTAIAQPTVKKDAGAELRRLNQSEVRANTQTRF...,MPINRPAFNLKLNTAIAQPTVKKDAGAELRRLNQSEVRANTQTRFA...,54,IDP
488,HopAI1n <unknown description>_1_94,HopAI1n <unknown description>,1,94,94,27.39,65.57,0.408,0.519,6.432,...,0.064,0.160,0.064,0.053,0.362,0.298,MPINRPAFNLKLNTAIAQPTVKKDAGAELRRLNQSEVRANTQTRF...,MPINRPAFNLKLNTAIAQPTVKKDAGAELRRLNQSEVRANTQTRFA...,94,IDP
491,HopAS1g <unknown description>_1_82,HopAS1g <unknown description>,1,82,82,29.22,69.58,0.454,0.567,6.573,...,0.037,0.110,0.024,0.146,0.415,0.268,MTLRINTRSATPVVPLETGSSSQPAVPSVTARPTEPPPVANPAAP...,MTLRINTRSATPVVPLETGSSSQPAVPSVTARPTEPPPVANPAAPK...,82,IDP
497,HopAT1h <unknown description>_1_122,HopAT1h <unknown description>,1,122,122,33.55,78.10,0.407,0.521,6.868,...,0.098,0.098,0.033,0.098,0.393,0.270,MIKANSWSSNLNAYRILQEPQSLTEEPPPIQTICPVQPESMAPPE...,MIKANSWSSNLNAYRILQEPQSLTEEPPPIQTICPVQPESMAPPEH...,122,IDP
498,HopAU1b <unknown description>_1_88,HopAU1b <unknown description>,1,88,88,28.52,68.27,0.430,0.559,6.130,...,0.091,0.068,0.023,0.045,0.432,0.330,MKPVQSVSATQHYNPLTNLGQEASCSHEISGITQTEGMQATAATT...,MKPVQSVSATQHYNPLTNLGQEASCSHEISGITQTEGMQATAATTQ...,88,IDP
499,HopAZ1n <unknown description>_1_89,HopAZ1n <unknown description>,1,89,89,27.80,64.58,0.413,0.528,6.637,...,0.135,0.124,0.101,0.079,0.326,0.236,MTYGIRGGVGTSAYYTQPQPFDELKLKPEQIQEKTAKLMEKGYFT...,MTYGIRGGVGTSAYYTQPQPFDELKLKPEQIQEKTAKLMEKGYFTV...,89,IDP
500,HopAZ1s <unknown description>_1_145,HopAZ1s <unknown description>,1,145,145,37.41,88.70,0.423,0.542,6.493,...,0.090,0.152,0.062,0.069,0.359,0.262,MTYGIRGGVGTSAYYTQPQPFDELKLKPEQIQEKTAKLMEKGYFT...,MTYGIRGGVGTSAYYTQPQPFDELKLKPEQIQEKTAKLMEKGYFTV...,145,IDP
501,HopB1c <unknown description>_1_171,HopB1c <unknown description>,1,171,171,40.98,97.84,0.417,0.542,6.438,...,0.099,0.135,0.047,0.111,0.327,0.251,MRPVGGPAPGYYPPTYEAERPTAQAGNDRARSSQASSSPAASVAP...,MRPVGGPAPGYYPPTYEAERPTAQAGNDRARSSQASSSPAASVAPE...,171,IDP
505,HopBA1b <unknown description>_1_66,HopBA1b <unknown description>,1,66,66,23.33,56.87,0.410,0.547,6.167,...,0.061,0.136,0.061,0.015,0.212,0.485,MVVEQPKTTMQKILYMKKRLALNAAWDAAAAREASAVCANKSMVW...,MVVEQPKTTMQKILYMKKRLALNAAWDAAAAREASAVCANKSMVWA...,66,IDP
519,HopBP1d <unknown description>_1_82,HopBP1d <unknown description>,1,82,82,24.84,56.78,0.399,0.510,6.792,...,0.061,0.122,0.061,0.049,0.488,0.220,MNISGLNRRQGTQAENTEGASSSVNTPQPQRGAGRRLQRQDALPT...,MNISGLNRRQGTQAENTEGASSSVNTPQPQRGAGRRLQRQDALPTD...,82,IDP
522,HopBR1a <unknown description>_1_133,HopBR1a <unknown description>,1,133,133,33.40,78.59,0.418,0.520,6.511,...,0.053,0.098,0.075,0.045,0.398,0.316,MPKISSFFGGGSSVQSFDATVQHYHSDETVHGTFNASQLGLHSYQ...,MPKISSFFGGGSSVQSFDATVQHYHSDETVHGTFNASQLGLHSYQR...,133,IDP
523,HopBS1a <unknown description>_1_52,HopBS1a <unknown description>,1,52,52,22.61,53.04,0.462,0.564,6.853,...,0.096,0.038,0.038,0.115,0.365,0.327,MIKANSWSSNLDAYRILQGPESLTEELPPIQTICLVQPESMAPPS...,MIKANSWSSNLDAYRILQGPESLTEELPPIQTICLVQPESMAPPSI...,52,IDP
537,HopF3b <unknown description>_1_96,HopF3b <unknown description>,1,96,96,28.79,68.67,0.408,0.539,6.708,...,0.083,0.125,0.073,0.062,0.417,0.219,MGICASSSRNQYSPTVSSTCSPQHVASHGNLASSGGNRITSVDQL...,MGICASSSRNQYSPTVSSTCSPQHVASHGNLASSGGNRITSVDQLN...,96,IDP
539,HopG1e <unknown description>_1_96,HopG1e <unknown description>,1,96,96,27.78,60.28,0.420,0.523,6.577,...,0.042,0.115,0.125,0.031,0.406,0.281,MQIKNSHLYSASRMVQNTFNASPKIEATNTIAKNNEPAAMSATQT...,MQIKNSHLYSASRMVQNTFNASPKIEATNTIAKNNEPAAMSATQTA...,96,IDP
540,HopG1f <unknown description>_1_78,HopG1f <unknown description>,1,78,78,25.00,59.01,0.431,0.544,6.145,...,0.051,0.115,0.051,0.000,0.487,0.295,MQIRNSHLYSASRLVQNTFNASSTKEAANTIAKNNESAALSATQT...,MQIRNSHLYSASRLVQNTFNASSTKEAANTIAKNNESAALSATQTA...,78,IDP
554,HopM1i <unknown description>_1_61,HopM1i <unknown description>,1,61,61,23.99,57.55,0.459,0.548,6.421,...,0.033,0.115,0.000,0.131,0.426,0.295,MNTPRIGGSGGIELARINQQHDAISAQTAHPNAVTPGMNPPLTPI...,MNTPRIGGSGGIELARINQQHDAISAQTAHPNAVTPGMNPPLTPIR...,61,IDP
559,HopO1e <unknown description>_1_54,HopO1e <unknown description>,1,54,54,20.96,51.29,0.426,0.536,6.571,...,0.204,0.185,0.074,0.074,0.204,0.259,MIVQERKRLKSQPKSLASDIERPDSMIKKAFDEKDGHPFGERFSD...,MIVQERKRLKSQPKSLASDIERPDSMIKKAFDEKDGHPFGERFSDD...,54,IDP
581,HopX1j <unknown description>_1_382,HopX1j <unknown description>,1,382,382,60.88,143.37,0.395,0.533,6.755,...,0.123,0.123,0.039,0.055,0.335,0.319,MRIHSSGHGISGPVSSAETVEKAVQSSAQAQNEASHSGPSEHPES...,MRIHSSGHGISGPVSSAETVEKAVQSSAQAQNEASHSGPSEHPESR...,382,IDP
584,HopZ1f <unknown description>_1_59,HopZ1f <unknown description>,1,59,59,22.70,54.43,0.426,0.549,6.453,...,0.102,0.169,0.017,0.068,0.390,0.237,MGNVCVSGSRMSQHVYSPERADAPPRSTLNTTERSQRTAGDADRN...,MGNVCVSGSRMSQHVYSPERADAPPRSTLNTTERSQRTAGDADRNH...,59,IDP
587,HopZ1k <unknown description>_1_99,HopZ1k <unknown description>,1,99,99,28.64,70.40,0.427,0.542,6.474,...,0.081,0.152,0.061,0.040,0.374,0.293,MKAYGQAAIDRASGKKTSASFAKLDATHLLDMINAENQRNSDLNL...,MKAYGQAAIDRASGKKTSASFAKLDATHLLDMINAENQRNSDLNLR...,99,IDP

In [27]:
merged_df.to_csv('/home/wenyuantong/Desktop/data/psytec_IDR_location.csv', index=True)