In [60]:
import numpy as np
import matplotlib

import matplotlib.pyplot as plt
from matplotlib.pyplot import figure

import pandas as pd

import re

In [61]:
# get RIN4

# Replace 'your_file.csv' with the actual path to your CSV file
csv_file_path = '/home/wenyuantong/Desktop/data/arabi_IDR_location.csv'

try:
    # Read the CSV file into a DataFrame
    merged_df = pd.read_csv(csv_file_path)

    print(f"Successfully loaded '{csv_file_path}' into a DataFrame.")
    # Display the first 5 rows of the DataFrame
    display(merged_df.head())

except FileNotFoundError:
    print(f"Error: The file '{csv_file_path}' was not found.")
except Exception as e:
    print(f"An error occurred while reading the CSV file: {e}")

Successfully loaded '/home/wenyuantong/Desktop/data/arabi_IDR_location.csv' into a DataFrame.

,Unnamed: 0,IDR ID,FASTA header,IDR start,IDR end,IDR len,Rg (A),Re (A),asphericity,scaling_exponent,...,fract_negative,fract_positive,fract_aro,fract_pro,fract_polar,fract_ali,sequence,Sequence_protein,Sequence Length,location
0,0,tr|A0A1P8B415|A0A1P8B415_ARATH Triglyceride li...,tr|A0A1P8B415|A0A1P8B415_ARATH Triglyceride li...,1,66,66,23.80,55.49,0.404,0.535,...,0.076,0.197,0.121,0.076,0.303,0.212,MTSLQLHFSVHFLRPKHRLRYSPIFNTRTFNFPGKITFRLRAKPN...,MTSLQLHFSVHFLRPKHRLRYSPIFNTRTFNFPGKITFRLRAKPNS...,854,N-terminal
1,1,tr|A0A1P8B415|A0A1P8B415_ARATH Triglyceride li...,tr|A0A1P8B415|A0A1P8B415_ARATH Triglyceride li...,306,525,220,47.99,115.33,0.419,0.569,...,0.191,0.095,0.027,0.023,0.395,0.268,APLKNTELLNNTAEDSEGASSEDSSDQHRSTNLSSSGKLSKDKDG...,MTSLQLHFSVHFLRPKHRLRYSPIFNTRTFNFPGKITFRLRAKPNS...,854,middle
2,2,sp|A4FVP2|TPS03_ARATH Terpenoid synthase 3; ch...,sp|A4FVP2|TPS03_ARATH Terpenoid synthase 3; ch...,1,34,34,16.55,40.86,0.455,0.568,...,0.029,0.265,0.059,0.118,0.382,0.147,MPKRQAQRRFTRKTDSKTPSQPLVSRRSANYQPS,MPKRQAQRRFTRKTDSKTPSQPLVSRRSANYQPSLWQHEYLLSLGN...,565,N-terminal
3,3,sp|F4I316|SUN3_ARATH SUN domain-containing pro...,sp|F4I316|SUN3_ARATH SUN domain-containing pro...,1,292,292,54.52,122.24,0.427,0.552,...,0.164,0.123,0.058,0.027,0.384,0.240,MQRSCRTRRRVSVNKFNGRNSFYKVSLSLVFLLWVLLFFSTLLIS...,MQRSCRTRRRVSVNKFNGRNSFYKVSLSLVFLLWVLLFFSTLLISH...,660,N-terminal
4,4,sp|F4I316|SUN3_ARATH SUN domain-containing pro...,sp|F4I316|SUN3_ARATH SUN domain-containing pro...,415,496,82,28.27,67.04,0.438,0.561,...,0.220,0.171,0.012,0.085,0.317,0.195,DNKNAYKPREGDSEHKEKPMQQIESLEGDDGADKSTHREKEKEAP...,MQRSCRTRRRVSVNKFNGRNSFYKVSLSLVFLLWVLLFFSTLLISH...,660,middle

In [6]:
merged_df.columns

Index(['Unnamed: 0', 'IDR ID', ' FASTA header', ' IDR start', ' IDR end',
       ' IDR len', ' Rg (A)', ' Re (A)', ' asphericity', ' scaling_exponent',
       ' prefactor', ' FCR', ' NCPR', ' kappa', ' fract_negative',
       ' fract_positive', ' fract_aro', ' fract_pro', ' fract_polar',
       ' fract_ali', ' sequence', 'Sequence_protein', 'Sequence Length',
       'location'],
      dtype='object')

In [62]:
# Define the word to search for
search_word = 'Q9LD45'


# Filter the DataFrame
filtered_df = merged_df[merged_df['IDR ID'].str.contains(search_word, case=False, na=False)]

print(f"\nDataFrame filtered for rows containing '{search_word}':")
display(filtered_df)

DataFrame filtered for rows containing 'Q9LD45':

Empty DataFrame
Columns: [Unnamed: 0, IDR ID,  FASTA header,  IDR start,  IDR end,  IDR len,  Rg (A),  Re (A),  asphericity,  scaling_exponent,  prefactor,  FCR,  NCPR,  kappa,  fract_negative,  fract_positive,  fract_aro,  fract_pro,  fract_polar,  fract_ali,  sequence, Sequence_protein, Sequence Length, location]
Index: []

[0 rows x 24 columns]

In [34]:
# get RIN4

# Replace 'your_file.csv' with the actual path to your CSV file
csv_file_path = '/home/wenyuantong/Desktop/data/psytec_IDR_location.csv'

try:
    # Read the CSV file into a DataFrame
    psytec_df = pd.read_csv(csv_file_path)

    print(f"Successfully loaded '{csv_file_path}' into a DataFrame.")
    # Display the first 5 rows of the DataFrame
    display(psytec_df.head())

except FileNotFoundError:
    print(f"Error: The file '{csv_file_path}' was not found.")
except Exception as e:
    print(f"An error occurred while reading the CSV file: {e}")

Successfully loaded '/home/wenyuantong/Desktop/data/psytec_IDR_location.csv' into a DataFrame.

,Unnamed: 0,IDR ID,FASTA header,IDR start,IDR end,IDR len,Rg (A),Re (A),asphericity,scaling_exponent,...,fract_negative,fract_positive,fract_aro,fract_pro,fract_polar,fract_ali,sequence,Sequence_protein,Sequence Length,location
0,0,HopX1a <unknown description>_1_88,HopX1a <unknown description>,1,88,88,28.94,70.23,0.439,0.554,...,0.057,0.091,0.034,0.125,0.432,0.250,MRIHSAGHSLPAPGPSVETTEKAVQSSSAQNPASCSSQTERPEAG...,MRIHSAGHSLPAPGPSVETTEKAVQSSSAQNPASCSSQTERPEAGS...,381,N-terminal
1,1,HopX1a <unknown description>_200_247,HopX1a <unknown description>,200,247,48,19.47,47.56,0.427,0.548,...,0.167,0.083,0.042,0.083,0.333,0.292,SPREKIHLAEQPGKDHVWAETDNSSAGSSPIVMDPWSNGAAILAEDSR,MRIHSAGHSLPAPGPSVETTEKAVQSSSAQNPASCSSQTERPEAGS...,381,Middle
2,2,HopX1a <unknown description>_298_380,HopX1a <unknown description>,298,380,83,27.59,66.03,0.435,0.550,...,0.120,0.181,0.024,0.072,0.253,0.349,NVSPLEGGRYQPEKSVLDEAFARRVSDKLNSDDPRRALQMEIEAV...,MRIHSAGHSLPAPGPSVETTEKAVQSSSAQNPASCSSQTERPEAGS...,381,C-terminal
3,3,HopX1c <unknown description>_1_87,HopX1c <unknown description>,1,87,87,28.95,70.08,0.427,0.550,...,0.046,0.080,0.034,0.161,0.437,0.241,MKIHNSGLTPPLPGISNGNVGKAAQSSMTQPQSQQGSHSLPPESS...,MKIHNSGLTPPLPGISNGNVGKAAQSSMTQPQSQQGSHSLPPESSE...,385,N-terminal
4,4,HopX1c <unknown description>_212_267,HopX1c <unknown description>,212,267,56,20.48,48.39,0.425,0.535,...,0.196,0.071,0.089,0.018,0.393,0.232,ASTEEDHVWAETDESQSGTSTIVMDPWSNGSAIFAEDSRFAKNRN...,MKIHNSGLTPPLPGISNGNVGKAAQSSMTQPQSQQGSHSLPPESSE...,385,Middle

In [49]:
# Define the word to search for
search_word = 'BI1'

# Filter the DataFrame
df1 = psytec_df[psytec_df['IDR ID'].str.contains(search_word, case=False, na=False)]

print(f"\nDataFrame filtered for rows containing '{search_word}':")
display(df1)

DataFrame filtered for rows containing 'BI1':

,Unnamed: 0,IDR ID,FASTA header,IDR start,IDR end,IDR len,Rg (A),Re (A),asphericity,scaling_exponent,...,fract_polar,fract_ali,sequence,Sequence_protein,Sequence Length,location,0,1,2,3
270,270.0,HopBI1b <unknown description>_1_80,HopBI1b <unknown description>,1.0,80.0,80.0,27.71,67.25,0.438,0.562,...,0.413,0.312,MRSTLSIPVTKTSVVNDYQQPVAVSAAPAPAPAPSSQLDKTSGTT...,MRSTLSIPVTKTSVVNDYQQPVAVSAAPAPAPAPSSQLDKTSGTTS...,435.0,N-terminal,NaN,NaN,NaN,NaN
271,271.0,HopBI1a <unknown description>_1_79,HopBI1a <unknown description>,1.0,79.0,79.0,27.91,66.81,0.442,0.565,...,0.418,0.253,MRSTLSIPVSKTSVFNDYQQPAAVVSAPTPTPTPSSPIDKKTGTT...,MRSTLSIPVSKTSVFNDYQQPAAVVSAPTPTPTPSSPIDKKTGTTS...,435.0,N-terminal,NaN,NaN,NaN,NaN

In [15]:
filtered_df = pd.concat([filtered_df, df1], ignore_index=True)

print("DataFrame after adding a new row:")
display(filtered_df)

DataFrame after adding a new row:

,Unnamed: 0,IDR ID,FASTA header,IDR start,IDR end,IDR len,Rg (A),Re (A),asphericity,scaling_exponent,...,fract_negative,fract_positive,fract_aro,fract_pro,fract_polar,fract_ali,sequence,Sequence_protein,Sequence Length,location
0,6178,sp|Q8GYN5|RIN4_ARATH RPM1-interacting protein ...,sp|Q8GYN5|RIN4_ARATH RPM1-interacting protein ...,1,211,211,42.98,100.31,0.393,0.522,...,0.123,0.152,0.071,0.085,0.412,0.142,MARSNVPKFGNWEAEENVPYTAYFDKARKTRAPGSKIMNPNDPEY...,MARSNVPKFGNWEAEENVPYTAYFDKARKTRAPGSKIMNPNDPEYN...,211,IDP
1,438,AvrRpt2a <unknown description>_1_109,AvrRpt2a <unknown description>,1,109,109,31.26,73.75,0.413,0.548,...,0.092,0.119,0.055,0.046,0.431,0.248,MKVFLSVTNHIPTSNQVDSLPEPDLAKRNSSESASGKKLAIQHSA...,MKVFLSVTNHIPTSNQVDSLPEPDLAKRNSSESASGKKLAIQHSAV...,258,N-terminal
2,439,AvrRpt2b <unknown description>_1_105,AvrRpt2b <unknown description>,1,105,105,31.26,75.30,0.405,0.555,...,0.095,0.133,0.038,0.067,0.381,0.286,MKIAPVAINHSPLSREVPSHAAPTQAKQTNLQSEAGDLDARKSSA...,MKIAPVAINHSPLSREVPSHAAPTQAKQTNLQSEAGDLDARKSSAS...,255,N-terminal
3,440,AvrRpt2c <unknown description>_1_104,AvrRpt2c <unknown description>,1,104,104,31.01,74.34,0.417,0.552,...,0.125,0.125,0.029,0.067,0.413,0.231,MQVGLSVTRHIPSSNEAHSVKEPELPNQNSSNSAEDEKTALKTSA...,MQVGLSVTRHIPSSNEAHSVKEPELPNQNSSNSAEDEKTALKTSAA...,255,N-terminal
4,153,AvrB2c <unknown description>_1_90,AvrB2c <unknown description>,1,90,90,28.23,66.89,0.418,0.551,...,0.111,0.100,0.044,0.067,0.389,0.267,MGNVCFRPSRSHVSQEFSQSEFSAASPVRTSERPSDASLDAGLES...,MGNVCFRPSRSHVSQEFSQSEFSAASPVRTSERPSDASLDAGLESS...,353,N-terminal
5,154,AvrB2g <unknown description>_1_111,AvrB2g <unknown description>,1,111,111,28.12,64.05,0.379,0.487,...,0.090,0.090,0.099,0.045,0.468,0.198,MGCASSNMSVSSSGSFRANSLNSPDHSRAEYSSVNSTSRSPRFGE...,MGCASSNMSVSSSGSFRANSLNSPDHSRAEYSSVNSTSRSPRFGEL...,329,N-terminal
6,155,AvrB2e <unknown description>_1_58,AvrB2e <unknown description>,1,58,58,21.69,52.38,0.432,0.554,...,0.069,0.103,0.034,0.052,0.552,0.172,MGCASSNMSVSSSGSFRANSLNSPDHSRAESSSVNSTSRSPRFGE...,MGCASSNMSVSSSGSFRANSLNSPDHSRAESSSVNSTSRSPRFGEL...,329,N-terminal
7,156,AvrB2d <unknown description>_1_52,AvrB2d <unknown description>,1,52,52,20.78,49.79,0.420,0.548,...,0.058,0.115,0.058,0.077,0.404,0.250,MGCVSSKASVISSDSFRASYTNSPEVSSVHQRARTPRCGELQGPQ...,MGCVSSKASVISSDSFRASYTNSPEVSSVHQRARTPRCGELQGPQV...,324,N-terminal
8,157,AvrB2a <unknown description>_1_50,AvrB2a <unknown description>,1,50,50,19.49,48.22,0.411,0.555,...,0.080,0.080,0.040,0.060,0.500,0.220,MGCITSKPLVSSPQWHNSATNSENLETGQRSHKASLYGAMSGSPE...,MGCITSKPLVSSPQWHNSATNSENLETGQRSHKASLYGAMSGSPER...,324,N-terminal
9,158,AvrB2b <unknown description>_1_42,AvrB2b <unknown description>,1,42,42,18.50,44.21,0.441,0.547,...,0.071,0.143,0.048,0.095,0.405,0.214,MGCISSKPQVMSPSRHYSSPDAEPATARTSHRRSARYGELSG,MGCISSKPQVMSPSRHYSSPDAEPATARTSHRRSARYGELSGPPAQ...,321,N-terminal
10,404,AvrB2f <unknown description>_1_44,AvrB2f <unknown description>,1,44,44,18.98,46.20,0.423,0.538,...,0.068,0.114,0.068,0.136,0.409,0.182,MGCISSKPQVMSPSRYYSSPDAEPATGRTSHRGSARYGELSGPP,MGCISSKPQVMSPSRYYSSPDAEPATGRTSHRGSARYGELSGPPAQ...,320,N-terminal
11,592,AvrB1b <unknown description>_1_31,AvrB1b <unknown description>,1,31,31,15.10,37.46,0.448,0.575,...,0.032,0.097,0.065,0.065,0.484,0.226,MGCVSSKSTTVLSPQTSFNEASRTSFRALPG,MGCVSSKSTTVLSPQTSFNEASRTSFRALPGPSQRQLEVYDQCLIG...,321,N-terminal
12,22,AvrRpm1a <unknown description>_1_228,AvrRpm1a <unknown description>,1,228,228,44.86,104.10,0.397,0.529,...,0.132,0.123,0.070,0.044,0.395,0.232,MGCVSSTSRSTGYYSGYESHEEPRAASRPTNSDDRGYETDSEPSS...,MGCVSSTSRSTGYYSGYESHEEPRAASRPTNSDDRGYETDSEPSSG...,229,N-terminal
13,23,AvrRpm1h <unknown description>_1_228,AvrRpm1h <unknown description>,1,228,228,44.52,103.14,0.399,0.529,...,0.140,0.132,0.079,0.035,0.377,0.232,MGCVSSTSRSTGYYSGYESHEEPRAASRTANSNERGYETDSEPSR...,MGCVSSTSRSTGYYSGYESHEEPRAASRTANSNERGYETDSEPSRD...,229,N-terminal
14,24,AvrRpm1d <unknown description>_1_100,AvrRpm1d <unknown description>,1,100,100,27.84,65.38,0.399,0.522,...,0.140,0.130,0.070,0.040,0.440,0.170,MGCVSSTSRSTGYYSGYESHDEPRVASSPANRHDRGYETDSEHSN...,MGCVSSTSRSTGYYSGYESHDEPRVASSPANRHDRGYETDSEHSND...,221,N-terminal
15,25,AvrRpm1e <unknown description>_1_55,AvrRpm1e <unknown description>,1,55,55,21.17,50.59,0.431,0.546,...,0.055,0.055,0.055,0.073,0.527,0.218,MGNICGTSGSHHVYSPPVSPRNVSGSSTPEYSAGGQALTSASHLS...,MGNICGTSGSHHVYSPPVSPRNVSGSSTPEYSAGGQALTSASHLSG...,226,N-terminal
16,26,AvrRpm1f <unknown description>_1_45,AvrRpm1f <unknown description>,1,45,45,19.24,46.01,0.455,0.546,...,0.022,0.022,0.044,0.089,0.556,0.244,VGNICGTSGSHHVYSPPVSPRNVSGSSTPAYSAGGQDLASASHLS,VGNICGTSGSHHVYSPPVSPRNVSGSSTPAYSAGGQDLASASHLSE...,224,N-terminal
17,27,AvrRpm1i <unknown description>_1_52,AvrRpm1i <unknown description>,1,52,52,20.61,48.36,0.441,0.540,...,0.058,0.038,0.058,0.077,0.538,0.212,MGNICGTSGSHHVYSPPVSPRNVSGSSTPEYSAGGQALTSASHLS...,MGNICGTSGSHHVYSPPVSPRNVSGSSTPEYSAGGQALTSASHLSG...,224,N-terminal
18,436,AvrRpm1c <unknown description>_1_51,AvrRpm1c <unknown description>,1,51,51,20.53,49.03,0.451,0.546,...,0.059,0.039,0.039,0.078,0.529,0.235,MGNICVTSGSHHVYSPPVSPRNVSGSSTPEYSAGGQALTSASHLS...,MGNICVTSGSHHVYSPPVSPRNVSGSSTPEYSAGGQALTSASHLSG...,176,N-terminal
19,437,AvrRpm1g <unknown description>_1_229,AvrRpm1g <unknown description>,1,229,229,43.46,99.61,0.397,0.520,...,0.122,0.118,0.079,0.031,0.419,0.231,MGYNVSNTSRNTGYYSGYESHQEPRGASSSSGNQHRGYEADSEQS...,MGYNVSNTSRNTGYYSGYESHQEPRGASSSSGNQHRGYEADSEQSG...,229,IDP

In [16]:
filtered_df.to_csv("/home/wenyuantong/Desktop/data/RIN4_effector_location.csv", index=True)

In [39]:
# Replace 'your_file.csv' with the actual path to your CSV file
csv_file_path = '/home/wenyuantong/Desktop/data/IDR_arabi_domain.tsv'

try:
    # Read the CSV file into a DataFrame
    dom2_df = pd.read_csv(csv_file_path, sep="\t", header=None)

    print(f"Successfully loaded '{csv_file_path}' into a DataFrame.")
    # Display the first 5 rows of the DataFrame
    display(dom2_df.head())

except FileNotFoundError:
    print(f"Error: The file '{csv_file_path}' was not found.")
except Exception as e:
    print(f"An error occurred while reading the CSV file: {e}")

Successfully loaded '/home/wenyuantong/Desktop/data/IDR_arabi_domain.tsv' into a DataFrame.

            0    1    2           3
0  A0A1P8B415    1   66  N-terminal
1  A0A1P8B415  306  525      middle
2      A4FVP2    1   34  N-terminal
3      F4I316    1  292  N-terminal
4      F4I316  415  496      middle

In [21]:
dom1_df.columns

Index([0, 1, 2, 3], dtype='int64')

In [40]:
# Define the word to search for
search_word = 'Q8GYN5'

# Filter the DataFrame
df2 = dom2_df[dom2_df[0].str.contains(search_word, case=False, na=False)]

print(f"\nDataFrame filtered for rows containing '{search_word}':")
display(df2)

DataFrame filtered for rows containing 'Q8GYN5':

           0  1    2    3
6178  Q8GYN5  1  211  IDP

In [30]:
#dom_all = df1
dom_all = pd.concat([dom_all, df1], ignore_index=True)

print("DataFrame after adding a new row:")
display(dom_all)

DataFrame after adding a new row:

            0  1    2           3
0   AvrRpm1a   1  228  N-terminal
1   AvrRpm1h   1  228  N-terminal
2   AvrRpm1d   1  100  N-terminal
3   AvrRpm1e   1   55  N-terminal
4   AvrRpm1f   1   45  N-terminal
5   AvrRpm1i   1   52  N-terminal
6   AvrRpm1c   1   51  N-terminal
7   AvrRpm1g   1  229         IDP
8     AvrB2c   1   90  N-terminal
9     AvrB2g   1  111  N-terminal
10    AvrB2e   1   58  N-terminal
11    AvrB2d   1   52  N-terminal
12    AvrB2a   1   50  N-terminal
13    AvrB2b   1   42  N-terminal
14    AvrB2f   1   44  N-terminal
15    AvrB1b   1   31  N-terminal
16  AvrRpt2a   1  109  N-terminal
17  AvrRpt2b   1  105  N-terminal
18  AvrRpt2c   1  104  N-terminal
19     Q8GYN5  1  211         IDP

In [31]:
dom_all.to_csv("/home/wenyuantong/Desktop/data/RIN4_domain.tsv", sep='\t', index=False)

In [37]:
# Replace 'your_file.csv' with the actual path to your CSV file
csv_file_path = '/home/wenyuantong/Desktop/data/IDR_psytec_domain.tsv'

try:
    # Read the CSV file into a DataFrame
    dom1_df = pd.read_csv(csv_file_path, sep="\t", header=None)

    print(f"Successfully loaded '{csv_file_path}' into a DataFrame.")
    # Display the first 5 rows of the DataFrame
    display(dom1_df.head())

except FileNotFoundError:
    print(f"Error: The file '{csv_file_path}' was not found.")
except Exception as e:
    print(f"An error occurred while reading the CSV file: {e}")

Successfully loaded '/home/wenyuantong/Desktop/data/IDR_psytec_domain.tsv' into a DataFrame.

         0    1    2           3
0  HopX1a     1   88  N-terminal
1  HopX1a   200  247      Middle
2  HopX1a   298  380  C-terminal
3  HopX1c     1   87  N-terminal
4  HopX1c   212  267      Middle

In [41]:
#dom_all = df1
dom1_df = pd.concat([dom1_df, df2], ignore_index=True)

print("DataFrame after adding a new row:")
display(dom1_df)

DataFrame after adding a new row:

           0    1    2           3
0    HopX1a     1   88  N-terminal
1    HopX1a   200  247      Middle
2    HopX1a   298  380  C-terminal
3    HopX1c     1   87  N-terminal
4    HopX1c   212  267      Middle
..       ...  ...  ...         ...
589  HopZ5a   252  346  C-terminal
590  HopZ5b     1   44  N-terminal
591  HopZ5b   283  346  C-terminal
592  AvrB1b     1   31  N-terminal
593   Q8GYN5    1  211         IDP

[594 rows x 4 columns]

In [43]:
dom1_df.to_csv("/home/wenyuantong/Desktop/data/RIN4_domain_all.tsv", sep='\t', index=False)