In [1]:
import numpy as np
import matplotlib

import matplotlib.pyplot as plt
from matplotlib.pyplot import figure

import pandas as pd

import re

In [3]:
#load in data of Arabidopsis x effector epsilon values
df1 = pd.read_csv("/home/wenyuantong/Desktop/data/all_cross/201_250.csv", index_col=0)
df1.head()

,AvrRpm1a_N-terminal_1_228,AvrRpm1h_N-terminal_1_228,HopW1n_C-terminal_704_922,HopY1h_N-terminal_1_214,HopBH1a_N-terminal_1_202,AvrE1f_N-terminal_1_226,AvrE1g_N-terminal_1_244,AvrE1s_N-terminal_1_213,HopF1d_N-terminal_1_216,HopM1v_C-terminal_555_765,...,Q56WK6_N-terminal_1_240,Q93YR9_middle_391_593,O80683_IDP_1_238,Q8LPT2_N-terminal_1_204,A0A1I9LNF2_N-terminal_1_245,O49403_C-terminal_186_401,Q9LXG8_N-terminal_1_212,Q9M158_C-terminal_252_466,Q9LMH6_N-terminal_1_214,Q9SV09_C-terminal_332_540
AvrRpm1a_N-terminal_1_228,3.024116,2.762555,5.532940,4.860486,7.987200,3.571176,4.059075,4.170456,4.472867,5.915386,...,17.023154,3.284009,4.055262,4.269205,7.376118,4.122273,7.346032,9.865983,2.686817,2.958846
AvrRpm1h_N-terminal_1_228,2.762555,2.504989,5.365991,4.610014,7.713466,3.156671,3.620491,3.800166,4.206680,5.591537,...,16.832543,2.960314,3.722694,4.018565,7.004048,3.898841,7.073705,9.609734,2.471605,2.731870
HopW1n_C-terminal_704_922,5.760322,5.586511,7.410715,7.483833,10.380154,8.148463,8.714421,8.363758,7.153484,8.747150,...,16.145694,6.730236,7.416846,7.320895,10.994301,5.351871,9.397123,11.143250,5.568914,4.938052
HopY1h_N-terminal_1_214,5.178462,4.911604,7.658689,7.932715,9.677644,7.802487,7.994177,8.162721,7.298236,7.941554,...,13.729049,6.539582,6.790024,7.189930,9.566719,4.325334,8.112995,10.209763,5.399028,4.272960
HopBH1a_N-terminal_1_202,9.015255,8.706288,11.253731,10.252553,13.084278,9.531320,10.385852,9.662052,10.043689,11.556320,...,22.637202,8.940613,10.649456,9.502036,13.870627,9.799725,12.690800,15.544494,8.090028,8.544257

In [ ]:
# Define the substring to search for
substring_to_find = 'Q8GYN5'

# Filter the DataFrame to get rows where 'item_description' contains the substring
# The `case=False` argument makes the search case-insensitive
# The `na=False` argument treats NaN values as not containing the substring
sub_df = df2[df2['A0A1P8B415'].str.contains(substring_to_find, case=False, na=False)]

print(f"\nSub-DataFrame containing '{substring_to_find}' in 'item_description' column:")
display(sub_df)

In [4]:
df = df1.filter(like='Q8GYN5')

In [5]:
df

                           Q8GYN5_IDP_1_211
AvrRpm1a_N-terminal_1_228          0.835527
AvrRpm1h_N-terminal_1_228          0.504634
HopW1n_C-terminal_704_922          4.984431
HopY1h_N-terminal_1_214            4.237097
HopBH1a_N-terminal_1_202           6.445527
...                                     ...
O49403_C-terminal_186_401          1.192396
Q9LXG8_N-terminal_1_212            4.593717
Q9M158_C-terminal_252_466          7.663339
Q9LMH6_N-terminal_1_214            1.015254
Q9SV09_C-terminal_332_540          0.739066

[1049 rows x 1 columns]

In [6]:
df.sort_values(by='Q8GYN5_IDP_1_211', inplace=True)

/tmp/ipykernel_945254/2535829909.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.sort_values(by='Q8GYN5_IDP_1_211', inplace=True)

In [7]:
df

                            Q8GYN5_IDP_1_211
Q9FQ03_C-terminal_802_1020         -8.157281
Q93VA8_C-terminal_139_350          -7.865370
O49429_C-terminal_180_419          -7.813558
Q9ZQE5_N-terminal_1_207            -7.186066
Q9FMH4_N-terminal_1_219            -6.629408
...                                      ...
Q56WK6_N-terminal_1_240            10.769765
Q94C59_N-terminal_1_205            10.945014
Q9SUA1_middle_454_680              11.024089
Q93ZQ2_C-terminal_402_641          11.025964
Q8GUP3_C-terminal_658_873          11.908921

[1049 rows x 1 columns]

In [11]:
df_negative = df[df['Q8GYN5_IDP_1_211'] < 0]

df_negative

                            Q8GYN5_IDP_1_211
Q9FQ03_C-terminal_802_1020         -8.157281
Q93VA8_C-terminal_139_350          -7.865370
O49429_C-terminal_180_419          -7.813558
Q9ZQE5_N-terminal_1_207            -7.186066
Q9FMH4_N-terminal_1_219            -6.629408
...                                      ...
Q9FYG7_C-terminal_149_359          -0.107623
O65420_middle_113_330              -0.052412
AvrRpm1g_IDP_1_229                 -0.050004
B9DFV2_middle_78_288               -0.045955
O49404_C-terminal_76_284           -0.031954

[268 rows x 1 columns]

In [12]:
file_name = '/home/wenyuantong/Downloads/RIN4_sorted_epsilons.xlsx'
df.to_excel(file_name, index=True)